import { ASSESSMENT_CONFIG_IDS, ASSESSMENT_CONFIG_NAMES, DBType } from '../../../../../utils/consts';
import { resolveImpactedResourceConfigName } from '../../../../WellArchitectedTab/assessmentFormatUtils';

/**
 * Config names handled by getMssqlImpactedResources — keep in sync with its switch cases.
 * @see ImpactedResourceDialog.tsx getMssqlImpactedResources
 */
export const MSSQL_IMPACTED_RESOURCE_DIALOG_CONFIG_NAMES = new Set<string>([
    ASSESSMENT_CONFIG_IDS.STORAGE_TIER,
    ASSESSMENT_CONFIG_NAMES.STORAGE_TIER,
    ASSESSMENT_CONFIG_IDS.LOG_DRIVE_SIZE,
    ASSESSMENT_CONFIG_IDS.TEMPDB_DRIVE_SIZE,
    ASSESSMENT_CONFIG_IDS.DATA_FILES_MDF,
    ASSESSMENT_CONFIG_IDS.LOG_FILES_LDF,
    ASSESSMENT_CONFIG_IDS.TEMPDB_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.SCHEDULED_LOCAL_SNAPSHOT,
    ASSESSMENT_CONFIG_IDS.SNAPCENTER_SNAPSHOT,
    ASSESSMENT_CONFIG_IDS.CRR,
    ASSESSMENT_CONFIG_IDS.SCHEDULED_FSX_FOR_ONTAP_BACKUPS,
    ASSESSMENT_CONFIG_IDS.OS_TYPE,
    ASSESSMENT_CONFIG_NAMES.OS_TYPE,
    ASSESSMENT_CONFIG_IDS.THIN_PROVISIONING,
    ASSESSMENT_CONFIG_NAMES.THIN_PROVISIONING,
    ASSESSMENT_CONFIG_IDS.AUTOSIZE,
    ASSESSMENT_CONFIG_NAMES.AUTOSIZE,
    ASSESSMENT_CONFIG_IDS.FRACTIONAL_RESERVE,
    ASSESSMENT_CONFIG_NAMES.FRACTIONAL_RESERVE,
    ASSESSMENT_CONFIG_IDS.SNAPSHOT_AUTODELETE,
    ASSESSMENT_CONFIG_NAMES.SNAPSHOT_AUTODELETE,
    ASSESSMENT_CONFIG_IDS.SPACE_MANAGEMENT,
    ASSESSMENT_CONFIG_NAMES.SPACE_MANAGEMENT,
    ASSESSMENT_CONFIG_IDS.AUTOSIZE_MODE,
    ASSESSMENT_CONFIG_NAMES.AUTOSIZE_MODE,
    ASSESSMENT_CONFIG_IDS.SNAPSHOT_COPY_RESERVE,
    ASSESSMENT_CONFIG_NAMES.SNAPSHOT_COPY_RESERVE,
    ASSESSMENT_CONFIG_IDS.TIERING_POLICY,
    ASSESSMENT_CONFIG_NAMES.TIERING_POLICY,
    ASSESSMENT_CONFIG_IDS.TIERING_MINIMUM_COOLING_DAYS,
    ASSESSMENT_CONFIG_NAMES.TIERING_MINIMUM_COOLING_DAYS,
    ASSESSMENT_CONFIG_IDS.SPACE_RESERVATION,
    ASSESSMENT_CONFIG_NAMES.SPACE_RESERVATION,
    ASSESSMENT_CONFIG_IDS.SPACE_ALLOCATION,
    ASSESSMENT_CONFIG_NAMES.SPACE_ALLOCATION,
    ASSESSMENT_CONFIG_IDS.NTFS_ALLOCATION_UNIT_SIZE,
    ASSESSMENT_CONFIG_NAMES.NTFS_ALLOCATION_UNIT_SIZE,
    ASSESSMENT_CONFIG_IDS.MULTIPATH_IO_POLICY,
    ASSESSMENT_CONFIG_NAMES.MULTIPATH_IO_POLICY,
    ASSESSMENT_CONFIG_IDS.DRIVE_LETTER,
    ASSESSMENT_CONFIG_NAMES.DRIVE_LETTER,
    ASSESSMENT_CONFIG_IDS.SHARED_STORAGE,
    ASSESSMENT_CONFIG_NAMES.SHARED_STORAGE,
    ASSESSMENT_CONFIG_IDS.OPERATING_SYSTEM_PATCH,
    ASSESSMENT_CONFIG_NAMES.OPERATING_SYSTEM_PATCH,
    ASSESSMENT_CONFIG_IDS.MICROSOFT_SQL_SERVER_PATCH,
    ASSESSMENT_CONFIG_NAMES.MICROSOFT_SQL_SERVER_PATCH,
    ASSESSMENT_CONFIG_IDS.RSS_CONFIGURATION,
    ASSESSMENT_CONFIG_NAMES.RSS_CONFIGURATION,
    ASSESSMENT_CONFIG_IDS.MTU,
    ASSESSMENT_CONFIG_NAMES.MTU
]);

/**
 * Config names handled by getOracleImpactedResources — keep in sync with its switch cases.
 * @see ImpactedResourceDialog.tsx getOracleImpactedResources
 */
export const ORACLE_IMPACTED_RESOURCE_DIALOG_CONFIG_NAMES = new Set<string>([
    ASSESSMENT_CONFIG_IDS.THIN_PROVISIONING,
    ASSESSMENT_CONFIG_NAMES.THIN_PROVISIONING,
    ASSESSMENT_CONFIG_IDS.AUTOSIZE,
    ASSESSMENT_CONFIG_NAMES.AUTOSIZE,
    ASSESSMENT_CONFIG_IDS.AUTOSIZE_MODE,
    ASSESSMENT_CONFIG_NAMES.AUTOSIZE_MODE,
    ASSESSMENT_CONFIG_IDS.FRACTIONAL_RESERVE,
    ASSESSMENT_CONFIG_NAMES.FRACTIONAL_RESERVE,
    ASSESSMENT_CONFIG_IDS.SNAPSHOT_POLICY,
    ASSESSMENT_CONFIG_NAMES.SNAPSHOT_POLICY,
    ASSESSMENT_CONFIG_IDS.SCHEDULED_LOCAL_SNAPSHOT,
    ASSESSMENT_CONFIG_IDS.SNAPSHOT_COPY_RESERVE,
    ASSESSMENT_CONFIG_NAMES.SNAPSHOT_COPY_RESERVE,
    ASSESSMENT_CONFIG_IDS.SNAPSHOT_AUTODELETE,
    ASSESSMENT_CONFIG_NAMES.SNAPSHOT_AUTODELETE,
    ASSESSMENT_CONFIG_IDS.SPACE_MANAGEMENT,
    ASSESSMENT_CONFIG_NAMES.SPACE_MANAGEMENT,
    ASSESSMENT_CONFIG_IDS.TIERING_POLICY,
    ASSESSMENT_CONFIG_NAMES.TIERING_POLICY,
    ASSESSMENT_CONFIG_IDS.TIERING_MINIMUM_COOLING_DAYS,
    ASSESSMENT_CONFIG_NAMES.TIERING_MINIMUM_COOLING_DAYS,
    ASSESSMENT_CONFIG_IDS.COMPRESSION,
    ASSESSMENT_CONFIG_NAMES.COMPRESSION,
    ASSESSMENT_CONFIG_IDS.DEDUPLICATION,
    ASSESSMENT_CONFIG_NAMES.DEDUPLICATION,
    ASSESSMENT_CONFIG_IDS.COMPACTION,
    ASSESSMENT_CONFIG_NAMES.COMPACTION,
    ASSESSMENT_CONFIG_IDS.NFS_ROOTONLY,
    ASSESSMENT_CONFIG_NAMES.NFS_ROOTONLY,
    ASSESSMENT_CONFIG_IDS.EXPORT_POLICY,
    ASSESSMENT_CONFIG_NAMES.EXPORT_POLICY,
    ASSESSMENT_CONFIG_IDS.OS_TYPE,
    ASSESSMENT_CONFIG_NAMES.OS_TYPE,
    ASSESSMENT_CONFIG_IDS.SPACE_RESERVATION,
    ASSESSMENT_CONFIG_NAMES.SPACE_RESERVATION,
    ASSESSMENT_CONFIG_IDS.SPACE_ALLOCATION,
    ASSESSMENT_CONFIG_NAMES.SPACE_ALLOCATION,
    ASSESSMENT_CONFIG_IDS.DNFS_CONFIGURATION_FILE,
    ASSESSMENT_CONFIG_NAMES.DNFS_CONFIGURATION_FILE,
    ASSESSMENT_CONFIG_IDS.DNFS_NO_SHARED_CACHE,
    ASSESSMENT_CONFIG_NAMES.DNFS_NO_SHARED_CACHE,
    ASSESSMENT_CONFIG_IDS.NFS_MOUNT_OPTIONS_DATABASEFILES,
    ASSESSMENT_CONFIG_NAMES.NFS_MOUNT_OPTIONS_DATABASEFILES,
    ASSESSMENT_CONFIG_IDS.OPERATING_SYSTEM_PATCH,
    ASSESSMENT_CONFIG_NAMES.OPERATING_SYSTEM_PATCH,
    ASSESSMENT_CONFIG_IDS.ORACLE_SECURITY_PATCH,
    ASSESSMENT_CONFIG_NAMES.ORACLE_SECURITY_PATCH,
    ASSESSMENT_CONFIG_IDS.CRR,
    ASSESSMENT_CONFIG_IDS.SNAPCENTER_SNAPSHOT,
    ASSESSMENT_CONFIG_IDS.SCHEDULED_FSX_FOR_ONTAP_BACKUPS,
    ASSESSMENT_CONFIG_IDS.ORACLE_BINARY_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.DATAFILES_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.CONTROLFILES_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.REDO_LOGS_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.TEMP_LOGS_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.ARCHIVE_PLACEMENT,
    ASSESSMENT_CONFIG_IDS.TRANSPARENT_HUGEPAGES,
    ASSESSMENT_CONFIG_NAMES.TRANSPARENT_HUGEPAGES,
    ASSESSMENT_CONFIG_IDS.TCP_ADVANCED_OPTIONS,
    ASSESSMENT_CONFIG_NAMES.TCP_ADVANCED_OPTIONS,
    ASSESSMENT_CONFIG_IDS.FILESYSTEMS_IO_OPTIONS,
    ASSESSMENT_CONFIG_NAMES.FILESYSTEMS_IO_OPTIONS,
    ASSESSMENT_CONFIG_IDS.MULTIPATH_READCOUNT,
    ASSESSMENT_CONFIG_NAMES.MULTIPATH_READCOUNT
]);

/** Fix table showed count only for these before flat migration (no View button). */
export const FIX_TABLE_EXCLUDED_IMPACTED_VIEW_CONFIG_IDS = new Set<string>([
    ASSESSMENT_CONFIG_IDS.RSS_CONFIGURATION,
    ASSESSMENT_CONFIG_IDS.MTU
]);

export const getImpactedResourceConfigCandidates = (configName?: string): string[] => {
    if (!configName) {
        return [];
    }

    const resolved = resolveImpactedResourceConfigName(configName);
    return resolved === configName ? [configName] : [configName, resolved];
};

/** Whether the Fix table should show View for this config (matches pre-migration behavior). */
export const isFixTableImpactedViewSupported = (configId: string, engineType?: string): boolean => {
    if (!configId || !engineType) {
        return false;
    }

    if (FIX_TABLE_EXCLUDED_IMPACTED_VIEW_CONFIG_IDS.has(configId)) {
        return false;
    }

    const handlerSet =
        engineType === DBType.ORACLE
            ? ORACLE_IMPACTED_RESOURCE_DIALOG_CONFIG_NAMES
            : MSSQL_IMPACTED_RESOURCE_DIALOG_CONFIG_NAMES;

    return getImpactedResourceConfigCandidates(configId).some(candidate => handlerSet.has(candidate));
};
