apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: wlmdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"    
  name: wlmdb
spec:
  {{ if .Values.global.demoEnv }}
  replicas: 1
  {{ else }}
  replicas: 2
  {{ end }}
  selector:
    matchLabels:
      run: wlmdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: wlmdb
        vectorfilter: disabled
      annotations:  
{{ toYaml .Values.global.annotations | indent 10 }}          
    spec:
      {{ if .Values.global.demoEnv }}
      serviceAccountName: wlmdb-demo-sa
      {{ else }}
      serviceAccountName: wlmdb-secretmanager-sa
      {{ end }}
      {{ if .Values.global.NFSlogs }}
      volumes:
        - name: logs-disk
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvName }}
      {{ end }}
      containers:
      {{ if .Values.global.demoEnv }}
      - image: {{ .Values.image.registry }}:{{ .Values.infraversion }}
      {{ else }}
      - image: {{ .Values.global.accountID }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/wlmdb:{{ .Values.infraversion }}
      {{ end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: wlmdb
        envFrom:
        - configMapRef:
            name: wlmdb-config
        - configMapRef:
            name: dr-status
        env:
          {{ if .Values.global.NFSlogs }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          {{ end }}
        readinessProbe:
          httpGet:
            path: wlmdb/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: wlmdb/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        {{ if .Values.global.NFSlogs }}
        volumeMounts:
          - mountPath: "/log"
            subPathExpr: $(NODE_NAME)/$(POD_NAME)
            name: logs-disk
        {{ end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      # dnsPolicy: ClusterFirst
      # restartPolicy: Always
      # securityContext: {}
      # terminationGracePeriodSeconds: 30
