{{- if .Values.global.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: monitoring-kube-prometheus
  name: wlmdb-exporter
  namespace: {{ .Values.global.namespace }}
spec:
  endpoints:
  - port: http
    path: /health
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
  selector:
    matchExpressions:
    - key: run
      operator: In
      values:
      - wlmdb
{{- end }}