apiVersion: v1
kind: Service
metadata:
  labels:
    run: wlmdb
  name: {{ .Values.global.namespace }}-wlmdb
spec:
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    run: wlmdb
  type: ClusterIP
