{{ if and (not .Values.global.demoEnv) ( .Values.global.istioEnabled) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wlmdb-vs
  namespace: wlmdb
spec:
  hosts:
    - {{ .Values.global.bluexpDomain }}
  gateways:
    - istio-ingress/istio-api
  http:
    - match:
        - uri: 
            regex: '\/wlmdb.*'
        - uri: 
            regex: '\/accounts\/.*\/wlmdb\/v.*'
      route:
        - destination:
            host: wlmdb.wlmdb.svc.cluster.local
            port:
              number: 8085
{{ end }}