{{ if .Values.global.NFSlogs }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
      trident.netapp.io/shareFromPVC: vector/shared-pv
  name: {{ .Values.global.namespace }}
  namespace: {{ .Values.global.pvName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: trident-csi
{{ end }}