apiVersion: v1
kind: ConfigMap
metadata:
  name: wlmdb-config
data:
  AUTH0_AUDIENCE: api.cloud.netapp.com
  SECRET_NAME: wlmdb
  REGION: {{ .Values.global.region }}
  isActive: {{ .Values.global.isActive | quote }}
  isPrimary: {{ .Values.global.isPrimary | quote }}
  TRACE_EXPORTER_URL: http://signoz-otel-collector.signoz.svc.cluster.local:4318
  SIGNOZ_ENDPOINT: signoz-otel-collector.signoz.svc.cluster.local:4318/v1/traces
  WLMDB_BUCKET_REGION: {{ .Values.global.region }}
  NODE_ENV: {{ .Values.global.NODE_ENV }}
  {{ if eq .Values.global.environment "production" }}
  AUTH0_ENDPOINT: netapp-cloud-account.auth0.com
  CLOUD_MANAGER_ENDPOINT: api.bluexp.netapp.com
  WORKLOAD_FACTORY_ENDPOINT: api.workloads.netapp.com
  WLMDB_ABSOLUTE_ENDPOINT: console.bluexp.netapp.com
  KINESIS_STREAM_NAME: audit-service-prod-stream
  WLMDB_BUCKET_NAME: production.wlmdb.workloads.netapp.com
  {{ else }}
  AUTH0_ENDPOINT: staging-netapp-cloud-account.auth0.com
  CLOUD_MANAGER_ENDPOINT: staging.api.bluexp.netapp.com
  WORKLOAD_FACTORY_ENDPOINT: staging.api.workloads.netapp.com
  WLMDB_ABSOLUTE_ENDPOINT: staging.console.bluexp.netapp.com
  KINESIS_STREAM_NAME: audit-service-staging-stream
  WLMDB_BUCKET_NAME: staging.wlmdb.workloads.netapp.com
  {{ end }}
