{{ if .Values.global.NFSlogs }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
      trident.netapp.io/shareFromPVC: vector/shared-pv
  name: wlmdb-pv
  namespace: wlmdb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.configuration.storageclass }}
{{ end }}