const PSSCRIPT = 'C:\\SSM\\ExecuteQueryFromSSM.ps1';
const CONFIGURELUNSCRIPT = 'C:\\SSM\\Configure-LUNs.ps1';
const CREATEDBSCRIPT = 'C:\\SSM\\Create-Database.ps1';
const INITIALIZEDBSCRIPT = 'C:\\SSM\\NewDB_Initialize-Iscsidisk.ps1';
const CLEANUPSCRIPT = 'C:\\SSM\\Cleanup-ONTAP.ps1';
const SSM_RUN_POWERSHELL_SCRIPT_DOC = 'AWS-RunPowerShellScript';
const SSM_RUN_POWERSHELL_SCRIPT_DOC_VERSION = '1';
const DB_ROWS_COUNT = 75;
const SSM_QUERY_CONCURRENCY_LIMIT = 10;
const INVOKE_VIRTUAL_MOUNT = 'C:\\SSM\\Invoke-virtualmount.ps1';
const CREATE_SANDBOX = 'C:\\SSM\\Create-Sandbox.ps1';

export {
    DB_ROWS_COUNT,
    SSM_RUN_POWERSHELL_SCRIPT_DOC,
    SSM_RUN_POWERSHELL_SCRIPT_DOC_VERSION,
    PSSCRIPT,
    SSM_QUERY_CONCURRENCY_LIMIT,
    CONFIGURELUNSCRIPT,
    CREATEDBSCRIPT,
    INITIALIZEDBSCRIPT,
    CLEANUPSCRIPT,
    INVOKE_VIRTUAL_MOUNT,
    CREATE_SANDBOX
};
