export const SELECT_CONFIG = {
    STANDARD_CREATE: `Standard create`,
    EASY_CREATE: `Easy create`,
    STANDARD_CREATE_CONTENT: `You set all of the configuration options, including availability, security, backups, and maintenance.`,
    EASY_CREATE_CONTENT:
        'Use a recommended best-practice configuration. You can change most configuration options after you create the database.',
    COMING_SOON: 'Coming soon',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    PREVIOUS: 'Previous',
    WIZARD_HEADING: 'Create new Microsoft SQL server',
    LOAD_CONFIG: 'Load configuration',
    SAVE_CONFIG: 'Save configuration',
    SECURITY_GROUP: 'Security group',
    DISCOVER_SQL_SERVER: 'Discover Microsoft SQL Server',
    SAVE_CONFIG_SUCCESS: 'Configuration was saved successfully.',
    LOAD_CONFIG_SUCCESS: 'Configuration was loaded successfully.',
    NO_SAVED_CONFIG: 'There are no saved configurations.',
    DUPLICATE_SAVED_CONFIG: 'Configuration was already saved.',
    MISSING_FIELDS_MESSAGE:
        'One or more fields that were loaded no longer exist. These fields are marked as "Action Required" and should be completed before you create the Microsoft SQL Server deployment.',
    DUPLICATE_CONFIG_NAME: 'A saved configuration with that name already exists. Try again with a different name.'
};

export const GENERAL = {
    LOADING_DATA: 'Loading data',
    ESTIMATED_COST_HEADER: 'The estimated cost will appear after you complete this form',
    COST_ERROR: 'Error while fetching cost information',
    AWS_CREDENTIALS: 'AWS credentials',
    NO_CREDENTIALS: 'No credentials are available',
    ACTION_REQUIRED: 'Action Required',
    ONE_OR_MORE_ERROR: 'One or more fields has an error',
    APPLICATION_SETTINGS: 'Application settings',
    OPERATING_SYSTEM: 'Operating system',
    DATABASE_DEPLOYMENT_MODEL: 'Database deployment model',
    DATABASE_EDITION: 'Database edition',
    DATABASE_VERSION: 'Database version',
    LICENSE: 'License',
    DATABASE_NAME: 'Database name',
    DATABASE_CREDENTIALS: 'Database credentials',
    CONNECTIVITY: 'Connectivity',
    KEY_PAIR: 'Key pair',
    KEY_PAIR_TEXT: 'Choose a key pair, which allows you to securely connect to your instance.',
    ACTIVE_DIRECTORY: 'Active Directory',
    INFRASTRUCTURE_SETTINGS: 'Infrastructure settings',
    COST: 'Cost',
    SUMMARY: 'Summary',
    INSTANCE_TYPE: 'DB Instance type',
    FSXN_SYSTEM: 'FSx for ONTAP system',
    STORAGE_CAPACITY: 'Data drive size',
    PROVISIONED_IOPS: 'Provisioned IOPS',
    THROUGHPUT_CAPACITY: 'Throughput capacity',
    ENCRYPTION: 'Encryption',
    TAGS: 'Tags',
    TAG: 'Tag',
    SIMPLE_NOTIFICATION_SERVICE: 'Simple Notification Service',
    SAVE_FORM_AS_CLOUD: 'Redirect to CloudFormation',
    AWS_SETTINGS: 'AWS settings',
    VIEW_API_REQUEST: 'View API request',
    LOAD_CONFIG_HEADER: 'Load Microsoft SQL server configuration',
    LOAD_CONFIG_CONTENT:
        'Select the configuration that you want to load. You can change the parameters after it loads.',
    SAVE_CONFIG_HEADER: 'Save Microsoft SQL Server configuration',
    SAVE_CONFIG_CONTENT:
        'You can save this Microsoft SQL Server configuration and load the configuration later for a future Microsoft SQL Server deployment.',
    CONFIG_NAME: 'Configuration name',
    LOAD: 'Load',
    CLOSE: 'Close',
    REMOVE: 'Remove',
    SAVE: 'Save',
    API_REQUEST: 'API request',
    CANCEL: 'Cancel',
    DEFAULT_AWS_ACCOUNT_SUB_TEXT: 'No AWS credentials are available to create this configuration.',
    STEP_ONE: 'Step 1:',
    STEP_TWO: 'Step 2:',
    NAVIGATE_TO: 'Go to the',
    STEP_TWO_TEXT: 'Add the credentials required for deployment:',
    OPTION_ONE: 'To generate a CloudFormation stack for deployment from AWS, minimum permissions are required.',
    OPTION_TWO: 'To deploy the configuration from BlueXP, full permissions are required.',
    FOR_MORE_INFO: 'Learn more about the',
    AWS_ACCOUNT_SUB_TEXT:
        'Select credentials that grant BlueXP the permissions required to deploy and manage Microsoft SQL server and FSx for ONTAP.',
    AWS_ACCOUNT_DEFAULT_LIST_TWO:
        'If you prefer not to enter your account credentials, continue to fill the form below, and we will produce the applicable CloudFormation code that you can copy and operate by yourself.',
    AWS_DEFAULT_LIST_FIRST:
        "page and add the credentials that you'd like to use, so we could create the DB for you. Deployment will take about 2 hours.",
    GO_TO_THE: 'Go to the',
    REQUIRED_PERMISSION_LINK: 'required permissions and how to add AWS credentials',
    REQUIRED_PERMISSION_LINK_ACCOUNTS: 'required permissions',
    MS_SQL_REQUIRED: 'Microsoft SQL on FSxN for ONTAP required permissions',
    CREDENTIALS: 'Credentials page.',
    CREDENTIAL: 'Credentials.',
    CREDENTIAL_WITHOUT_DOT: 'Credentials',
    ADD_NEW_CREDENTIALS: 'To add a new credentials, visit',
    MULTI_AZ_CHECK_MESSAGE:
        'The selected VPC is not optimized. You should choose a VPC with subnets in 2 availability zones so that each cluster node will be in a dedicated availability zone.',
    QUERY_ERROR: 'Query error',
    PERMISSION_REQUIRED: 'Permissions required',
    CLOUDFORMATION_TEMPLATE_URL: ['CloudFormation template ', 'URL'],
    SAME_ROUTE_SUBNET_ERROR: 'AWS FSx requires route tables to be different for subnets in multi-zone deployment.',
    //Constants for Security group
    USE_AN_EXISTING_SECURITY: 'Use an existing security group',
    GENERATED_SECURITY_GROUP: 'Create a new security group',
    EXISTING_SECURITY_GROUP: 'Existing security group',
    //Constants for Op system
    WIN_SERVER_2016: 'Windows server 2016',
    WIN_SERVER_2019: 'Windows server 2019',
    WIN_SERVER_2016_VERSION: '2016',
    WIN_SERVER_2019_VERSION: '2019',
    OP_SYS_TEXT: 'Choose the operating system on which to install SQL Server.',
    //Constants for DB Deployment
    FAILOVER_CLUSTER: 'Failover cluster instance (FCI)',
    FAILOVER_CLUSTER_TEXT: 'Deploy your SQL Server Always On application across multiple Availability Zones',
    SINGLE_INSTANCE: 'Single Instance',
    SINGLE_INSTANCE_TEXT: 'Deploy your SQL Server on a single node.',
    //Constants for DB Edition
    SQL_SERVER_STANDARD: 'Standard',
    SQL_SERVER_STANDARD_EDITION: 'SQL Server Standard Edition',
    SQL_SERVER_STANDARD_EDITION_TEXT:
        'Core data management and business intelligence capabilities for mission-critical applications and mixed workloads.',
    SQL_SERVER_WEB: 'Web',
    SQL_SERVER_WEB_EDITION: 'SQL Server Web Edition',
    SQL_SERVER_WEB_EDITION_TEXT:
        "In accordance with Microsoft's licensing policies, it can only be used to support public and Internet-accessible webpages, websites, web applications, and web services.",
    SQL_SERVER_ENTERPRISE: 'Enterprise',
    SQL_SERVER_ENTERPRiSE_EDITION: 'SQL Server Enterprise Edition',
    SQL_SERVER_ENTERPRiSE_EDITION_TEXT:
        'Comprehensive high-end capabilities for mission-critical applications with demanding database workloads and business intelligence requirements.',
    //Constants for DB version
    SQL_SERVER_2019: 'SQL Server 2019',
    SQL_SERVER_2016: 'SQL Server 2016',
    SQL_SERVER_2022: 'SQL Server 2022',
    SQL_SERVER_2019_VERSION: '2019',
    SQL_SERVER_2016_VERSION: '2016',
    SQL_SERVER_2022_VERSION: '2022',
    VERSION: 'Version',
    //Constants for License accordion
    LICENSE_TEXT:
        'Use an AWS AMI (which includes a license) or bring your own SQL license (BYOL) through a custom AMI.',
    LICENSE_INCLUDED_AMI: 'License included AMI',
    VIEW_THE_REQ: 'View the requirements',
    LICENSE_ID: 'License ID',
    USE_CUSTOM_AMI: 'Use custom AMI',
    AMI_ID: 'AMI ID',
    SELECT_AMI_ID: 'Select AMI ID',
    SELECT_AMI_NAME: 'Select AMI Name',

    //Constants for DB name accordion
    DATABASE_INSTANCE_NAME: 'Database cluster name',
    DB_NAME_TOOLTIP:
        'The cluster name must be 15 characters or less. The first character can be a letter (a-z or A-Z) or a number (0-9). Subsequent characters can be a letter, number, or hyphen (-).',
    DB_NAME_TOOLTIP1: 'The cluster name must be 15 characters or less',
    DB_NAME_TOOLTIP2: 'The first character can be a letter (a-z or A-Z) or a number (0-9)',
    DB_NAME_TOOLTIP3: 'Subsequent characters can be a letter, number, or hyphen (-)',
    KEY_PAIR_NAME: 'Key pair',
    //Constants for Storage capacity
    CAPACITY: 'Capacity',
    UNIT: 'Unit',
    CAPACITY_TOOLTIP:
        'Specify the SQL data drive size only. The provisioning for log drive, tempdb, and other FSx for ONTAP file system volumes (including LUNs), will be performed according to NetApp best practices for SQL configuration. You can change the recommended defaults to meet your requirements.',
    ERROR_CAPACITY: 'The maximum supported capacity is 130 TiB.',
    //Provisioned IOPS
    AUTOMATIC: 'Automatic',
    USER_PROVISIONED: 'User-provisioned',
    IOPS_VALUE: 'IOPS value',
    AUTOMATIC_IOPS: '3 IOPS per GiB of SSD storage will be created.',
    PLACEHOLDER_PROVISIONED: '3072 - 160000 IOPS',
    THROUGHPUT: 'Throughput',
    //SIMPLE NOTIFICATION SERVICES
    SNS: 'Enable the Simple Notification Service (SNS) for this configuration',
    SNS_TEXT: 'Enter an SNS topic for Microsoft SQL Server to send notifications and alerts.',
    ARN: 'ARN',
    //Cloud watch
    CLOUD_WATCH_MONITORING: 'CloudWatch monitoring',
    CLOUD_WATCH_TEXT:
        'Set up monitors and automated insights for this SQL deployment using CloudWatch Application Insights.',
    //FSX Accordion
    CREATE_NEW_FSXN: 'Create new FSxN',
    CREATE_NEW_FSXN_SYSTEM: 'Create new file system',
    SELECT_EXISTING_FSX: 'Select an existing FSxN ',
    FSXN_NAME: 'FSxN name',
    USER_NAME: 'User name',
    FSX_PASSWORD: 'FSxN password',
    NOTICE: 'Notice:',
    NOTICE_FSX_TEXT: 'New filesystem provisioning adds another 30 minutes to the total installation time.',
    PASSWORD_FSX_1: 'The password must be at least eight characters long.',
    PASSWORD_FSX_2: 'The password must contain at least one letter and one number.',
    PASSWORD_FSX_3: 'The password cannot contain the user name.',
    //Active Directory
    DOMAIN_NAME: 'Domain name',
    DNS_ADDRESS: 'DNS address',
    AD_TEXT:
        'The directory in which you want to allow authorized users to authenticate with this SQL Server instance using Windows Authentication. Windows Server Failover Cluster requires that all servers be joined to the same Active Directory domain. Ensure that you have connection between the Active Directory and the VPC.',
    PASSWORD: 'Password',
    //Region VPC accordion
    REGION: 'Region',
    REGION_VPC_TEXT:
        'Choose the Virtual private cloud (VPC). The VPC defines the virtual  networking  environment for this DB instance.',
    SELECT_EXISTING_VPC: 'Select an existing VPC',
    CREATE_NEW_VPC: 'Create new VPC',
    REGION_VPC: 'Region & VPC',
    VPC: 'VPC',
    //Availability zone
    AZ_TEXT:
        'Select an Availability Zone and subnet for each node. Ensure that each of the selected private subnets have outbound connectivity enabled. The subnet for node 1 must be in the primary Availability Zone for the FSx for ONTAP file system.',
    CLUSTER_CONFIG_NODE_1: 'Cluster configuration - Node 1:',
    CLUSTER_CONFIG_NODE_2: 'Cluster configuration - Node 2:',
    AZ_Zone: 'Availability zone',
    SUBNET: 'Subnet',
    //DB credential
    DATABASE_CREDENTIAL_TEXT: 'Create a new service account for SQL Server.',
    USERNAME_TOOLTIP:
        'The user name must contain at least 5 alphanumeric characters. The user name can\'t be "admin" or "administrator".',
    USERNAME_TOOLTIP1: 'The user name must contain at least 5 alphanumeric characters.',
    USERNAME_TOOLTIP2: 'The user name can\'t be "admin" or "administrator".',

    PASSWORD_CRED_1:
        'The password must be between 8 and 128 characters in length and contain characters from three of the following four categories: ',
    PASSWORD_CRED_LI_1: 'Uppercase letters (A-Z)',
    PASSWORD_CRED_LI_2: 'Lowercase letters (a-z)',
    PASSWORD_CRED_LI_3: 'Base 10 digits (0 through 9)',
    PASSWORD_CRED_LI_4:
        'Non-alphanumeric characters such as: exclamation point (!), dollar sign ($), number sign (#), or percent (%)',
    PASSWORD_CRED_4: "The password can't contain the user name.",
    //Encryption
    ENCRYPTION_TEXT:
        'Select the key to encrypt this database storage (FSx for ONTAP). You can select from master keys in your account or enter the ARN of a key from a different account.',
    ENCRYPTION_SELECT_FROM_ACCOUNT: 'Select a key from your account',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT: 'Select a key from another account',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT_TEXT:
        'If needed, you can select a customer-managed key from another AWS account by entering the Amazon Resource Name (ARN) of that key. You can find the ARN from the Amazon Key Management Service console. Key ARN starts with ‘arn:aws:kms’ or ‘arn:aws-us-gov:kms’.',
    ENCRYPTION_TEXT_FIELD: 'Encryption key ARN',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT_SUB_TEXT:
        'AWS is responsible for data encryption and decryption operations. Key management is handled by AWS Key Management Service.',
    CUSTOMER_MASTER_KEY_NAME: 'Key name',
    KEY_ID: 'Key ID',
    EXPIRATION_DATE: 'Expiration date',
    ORIGIN: 'Origin',
    ONLY_ENABLED_KEYS: 'Only enabled keys are displayed.',
    TAGS_HEADING_MSG: 'You can add upto 40 tags',
    ADD_NEW_TAG: '+ Add new tag',
    TAG_KEY: 'Tag key',
    TAG_VALUE: 'Tag value',
    TAG_KEY_PLACEHOLDER: 'Up to 127 characters',
    TAG_VALUE_PLACEHOLDER: 'Up to 255 characters',
    SELECT_ANY_ACCOUNT: 'Select your AWS credentials first',
    SELECT_ANY_VPC: 'This field will be enabled after you select a region and VPC.',
    SELECT_AZ: 'Select the Availability Zones first',
    CLOUD_FORMATION_URL_TEXT: 'The CloudFormation URL can be loaded using the',
    PASSWORD_ERROR_CHECK: 'Check password criteria',
    CREATE_INFO_MESSAGE: [
        'Microsoft SQL Server and FSxN for ONTAP deployment ',
        'with stack name ',
        ' has been triggered. You can track the progress using the ',
        'Timeline',
        '. Estimated time: Up to 2 hours. We will notify you as soon as the deployment is completed.'
    ],
    IP_DOMAIN: 'SQL Server IP address or domain name',
    AUTHENTICATION_TYPE: 'Authentication type',
    DISCOVER_FORM_HEADING:
        'Enter connection details for Microsoft SQL Server that is accessible from the BlueXP Connector',
    IS_REQUIRED_MSG: ' is required',
    DATABASES_SUMMARY: 'Databases summary',
    DATABASES: 'Databases',
    TOTAL_SIZE: 'Total size',
    INFORMATION: 'Information',
    RESOURCE_DISTRIBUTION: 'Resources Distribution',
    TIMELINE: 'Timeline',
    REMOVE_FROM_WORKSPACE: 'Remove from workspace',
    TABLES_SUMMARY: 'Tables summary',
    TABLES: 'Tables',
    //Estimation cost
    ESTIMATED_COST: 'Estimated cost',
    ESTIMATED_SUBTEXT: 'Estimate of charges incurred to deploy the following resources.',
    RESOURCES: 'Resources',
    AMOUNT_IN_USD: 'Amount in USD (monthly)',
    COMPUTE: 'Compute',
    INSTANCE_TYPE_EC: 'Instance type',
    QUANTITY: 'Quantity',
    STORAGE: 'Storage',
    TYPE: 'Type',
    SIZE: 'Size',
    ESTIMATED_MONTHLY_COST: 'Estimated monthly cost',
    EC_NOTE:
        'This is only an estimate of AWS costs to deploy additional resources and does not include any taxes or discounts that may apply. Actual fees depend on many factors, including actual usage of AWS services.',
    MS_SQL_CPU_USED: 'CPU used by Microsoft SQL Server',
    CPU_REM: 'CPU available and used by other processes',
    MS_SQL_MEMORY_USED: 'Memory used by Microsoft SQL Server',
    MEMORY_REM: 'Memory available and used by other processes',
    MS_SQL_DISK_USED: 'Storage used by Microsoft SQL Server',
    DISK_REM: 'Storage available and used by other processes',
    OVERVIEW: 'Overview',
    MSSQL: 'Microsoft SQL Server',
    REMOVE_DIALOG_CONTENT_FIRST_PART: (weType: string) => `You are about to remove the ${weType} working environment`,
    REMOVE_DIALOG_CONTENT_SECOND_PART: 'from workspace.',
    REMOVE_DIALOG_NOTICE: (weType: string) => `This will not affect the ${weType} instance.`,
    //PREVIEW DEFAULT
    PREVIEW_DEFAULT_TEXT:
        'Easy create sets the following configurations to their default values, some of which can be changed later. If you want to change any of these settings now, use',
    PD_HEADER_TEXT: 'View the default configuration created by the system',
    PREVIEW_DEFAULT: 'Preview default',
    EDITABLE_AFTER: 'Editable after creation',
    DEFAULT: 'Default',
    CONFIGURATION: 'Configuration',
    PD_DISABLED: 'Disabled',
    YES: 'Yes',
    PD_AUTO_CREATE: 'Automatically create based on user selection',
    NO: 'No',
    PD_CREATE_SECURITY: 'Create a security group for the user',
    PD_UPGRADED_MANUALLY: 'Yes (can be upgraded manually)',
    FIRST_IN_THE_LIST: 'First in the list',
    THROUGHPUT_DISABLE_TEXT: 'Throughput capacity is already set on the FSx for ONTAP file system. You can\'t change this value.',
    IOPS_DISABLE_TEXT: 'Provisioned IOPS is already set on the FSx for ONTAP file system. You can\'t change this value.',
    KMS_DISABLE_TEXT: 'Encryption Key is already set on the FSx for ONTAP file system. You can\'t change this value.'
};
