export const SELECT_CONFIG = {
    STANDARD_CREATE: 'Standard create',
    EASY_CREATE: 'Easy create',
    ADVANCED_CREATE: 'Advanced create',
    QUICK_CREATE: 'Quick create',
    STANDARD_CREATE_CONTENT:
        'You set all of the configuration options, including availability, security, backups, and maintenance.',
    EASY_CREATE_CONTENT:
        'Use a recommended best-practice configuration. You can change most configuration options after you create the database.',
    COMING_SOON: 'Coming soon',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    PREVIOUS: 'Previous',
    WIZARD_HEADING: 'Create new Microsoft SQL Server',
    LOAD_CONFIG: 'Load configuration',
    SAVE_CONFIG: 'Save configuration',
    SECURITY_GROUP: 'Security group',
    DISCOVER_SQL_SERVER: 'Discover Microsoft SQL Server',
    SAVE_CONFIG_SUCCESS: 'Configuration was saved successfully.',
    LOAD_CONFIG_SUCCESS: 'Configuration was loaded successfully.',
    NO_SAVED_CONFIG: 'There are no saved Microsoft SQL configurations.',
    NO_SAVED_CONFIG_PGSQL: 'There are no saved PostgreSQL configurations.',
    MAX_CONFIG_LIMIT:
        "You have reached the maximum limit of 100 configurations. Before you can save a new configuration, you'll need to delete an old configuration first.",
    DUPLICATE_SAVED_CONFIG: 'Configuration was already saved.',
    MISSING_FIELDS_MESSAGE:
        'One or more fields that were loaded no longer exist. These fields are marked as "Action Required" and should be completed before you create the Microsoft SQL Server deployment.',
    DUPLICATE_CONFIG_NAME: 'A saved configuration with that name already exists. Try again with a different name.'
};

export const GENERAL = {
    MANAGE_MIN_PERMISSION_REQUIRED: [
        'Missing minimum prerequisites:',
        ' At least one capability must meet the minimum prerequisites and be in "Ready" status before proceeding. To register this SQL Server instance, please address the necessary prerequisites and try again.'
    ],
    WELL_ARCHITECTED_STATUS: 'Well-architected status',
    UPDATE: 'Update',
    UPDATE_FSX_ADMIN_PASSWORD: 'Update fsxadmin password',
    ORACLE_FSX_PASSWORD_CONTENT:
        'The password for your fsxadmin user might have changed. Update credentials to maintain FSx for ONTAP operations serving this Oracle Server database.',
    FSX_PASSWORD_CONTENT:
        'The password for your fsxadmin user might have changed. Update credentials to maintain FSx for ONTAP operations serving this Microsoft SQL Server instance.',
    SQL_PASSWORD_CONTENT:
        'The password for your Windows login might have changed. Update credentials to register this Microsoft SQL Server instance.',
    ORACLE_PASSWORD_CONTENT:
        'The password for your Oracle login might have changed. Update credentials to register this  Oracle Server database.',
    ORACLE_ASM_PASSWORD_CONTENT:
        'The password for your Oracle ASM login might have changed. Update credentials to register this  Oracle ASM instance.',
    UPDATE_SQL_SERVER_PASSWORD: 'Update Microsoft SQL Server password',
    UPDATE_ORACLE_SERVER_PASSWORD: 'Update Oracle Server password',
    UPDATE_ORACLE_ASM_PASSWORD: 'Update Oracle ASM password',
    DATABASE_MANAGEMENT: 'Database management',
    DATABASE_OPTIMIZATION: 'Database optimization',
    INVENTORY_CARD_TEXT1:
        'Register database resources and perform day-to-day operations with FSx for ONTAP. You can check the status of hosts, instances, and databases, deploy new resources, and stay on top of resource usage, data protection, and performance.',
    INVENTORY_CARD_TEXT2:
        'Plus, get optimization recommendations to make sure your database resources are well-architected.',
    INVENTORY_CARD_TEXT3:
        'Automatically assess and mitigate issues in database infrastructure to keep your databases running smoothly and cost-effectively. Continuously scan deployments to get insights and recommendations to make sure everything aligns with vendor and industry best practices.',
    WELL_ARCHITECTED_BREAKDOWN_BY_CATEGORY: 'Score breakdown by categories',
    CPU_UTILIZATION: 'CPU utilization',
    CAPACITY_UTILIZATION: 'Capacity utilization',
    REACTIVATE_TOOLTIP: 'Restart the analysis for a postponed or dismissed configuration.',
    POSTPONED_TOOLTIP: 'Postpone the configuration analysis for 30 days.',
    DISMISS_TOOLTIP: 'Stop the configuration analysis.',
    ACTIVATING_MESSAGE: 'Active. Will be analyzed in the next analysis.',
    ACTIVATING_MESSAGE_TWO: 'Will be analyzed in the next analysis.',
    DISMISSED_MESSAGE: 'Analysis is dismissed.',
    CLONE_MANAGEMENT_REFRESH: 'Clone cleanup Refresh',
    CLONE_MANAGEMENT_DELETE: 'Clone cleanup Delete',
    ALL_CRED_SELECTED: 'All credentials selected',
    NO_CRED_SELECTED: 'No credentials selected',
    ALL_REGIONS_SELECTED: 'All regions selected',
    NO_REGIONS_SELECTED: 'No regions selected',
    ASSESSMENT_PERFORMED: 'Automatic daily analysis',
    LAST_UPDATE: 'Last update:',
    ASSESS_NOW: 'Analyze now',
    MICROSOFT_SQL_SERVER_TYPE: 'Microsoft SQL Server',
    POSTGRESQL_TYPE: 'PostgreSQL',
    ORACLE_TYPE: 'Oracle',
    ORACLE_ASM_TYPE: 'Oracle ASM',
    USER_DATABASE: 'User Database',
    SYSTEM_DATABASE: 'System Database',
    MULTIPLE_VALUES: 'Multiple values',
    OPTIMIZE: 'Fix',
    VIEW_AND_FIX: 'View and fix',
    REBASE_LINE: 'Re-baseline',
    APPLY: 'Apply',
    MICROSOFT_SQL: 'Microsoft SQL',
    FAILOVER_CLUSTER_INSTANCES: 'Failover Cluster Instances',
    LOADING_DATA: 'Loading data',
    ACTIVE_NODE: 'Active node',
    ESTIMATED_COST_HEADER: 'The estimated cost will appear after you complete this form',
    COST_ERROR: 'Error while fetching cost information',
    AWS_CREDENTIALS: 'AWS credentials',
    NO_CREDENTIALS: 'No credentials are available',
    ACTION_REQUIRED: 'Action Required',
    ONE_OR_MORE_ERROR: 'One or more fields has an error',
    APPLICATION_SETTINGS: 'Application settings',
    OPERATING_SYSTEM: 'Operating system',
    DATABASE_DEPLOYMENT_MODEL: 'Database deployment model',
    DATABASE_EDITION: 'Database edition',
    DATABASE_VERSION: 'Database version',
    POSTGRE_VERSON: 'PostgreSQL version',
    LICENSE: 'License',
    SQL_SERVER_INSTALL_TYPE: 'SQL Server install type',
    DATABASE_NAME: 'Database name',
    DATABASE_SERVER_NAME: 'Database Server name',
    DATABASE_CREDENTIALS: 'Database credentials',
    CONNECTIVITY: 'Connectivity',
    KEY_PAIR: 'Key pair',
    KEY_PAIR_TEXT: 'Choose a key pair, which allows you to securely connect to your instance.',
    ACTIVE_DIRECTORY: 'Active Directory',
    INFRASTRUCTURE_SETTINGS: 'Infrastructure settings',
    COST: 'Cost',
    SUMMARY: 'Summary',
    INSTANCE_TYPE: 'DB Instance type',
    SNAPSHOT_POLICY: 'Snapshot policy',
    DAILY_RETENTION: 'Daily (Retention 7 days)',
    DAILY_SNAPSHOT: 'Daily snapshot',
    RETENTION_SEVEN_DAYS: 'Retention: 7 days',
    NONE: 'None',
    FSXN_SYSTEM: 'FSx for ONTAP system',
    STORAGE_CAPACITY: 'Data drive size',
    PROVISIONED_IOPS: 'Provisioned IOPS',
    THROUGHPUT_CAPACITY: 'Throughput capacity',
    ENCRYPTION: 'Encryption',
    TAGS: 'Tags',
    TAG: 'Tag',
    SIMPLE_NOTIFICATION_SERVICE: 'Simple Notification Service',
    SAVE_FORM_AS_CLOUD: 'Redirect to CloudFormation',
    GO_TO_CLOUDFORMATION: 'Go to CloudFormation',
    DEPLOYMENT_MODEL: 'Deployment model',
    ACCESS_PROTOCOL: 'Access protocol:',
    AWS_SETTINGS: 'AWS settings',
    LANDING_ZONE: 'Landing zone',
    VIEW_API_REQUEST: 'View API request',
    LOAD_CONFIG_HEADER: 'Load Microsoft SQL Server configuration',
    LOAD_CONFIG_PGSQL_HEADER: 'Load PostgreSQL Server configuration',
    LOAD_CONFIG_CONTENT:
        'Select the configuration that you want to load. You can change the parameters after it loads.',
    SAVE_CONFIG_HEADER: 'Save Microsoft SQL Server configuration',
    SAVE_CONFIG_PGSQL_HEADER: 'Save PostgreSQL Server configuration',
    RENAME_CONFIG: 'Rename configuration',
    DELETE_CONFIG: 'Delete configuration',
    DELETE_CONFIG_TEXT: 'Are you sure to delete configuration',
    DELETE_CONFIG_NOTIFICATION: 'Configuration deleted successfully.',
    SAVE_CONFIG_CONTENT:
        'You can save this Microsoft SQL Server configuration and load the configuration later for a future Microsoft SQL Server deployment.',
    SAVE_CONFIG_PGSQL_CONTENT:
        'You can save this PostgreSQL Server configuration and load the configuration later for a future PostgreSQL Server deployment.',
    RENAME_CONFIG_CONTENT: ['Enter a new name for the ', ' configuration'],
    RENAME_CONFIG_NOTIFICATION: 'Configuration name changed successfully.',
    CONFIG_NAME: 'Configuration name',
    LOAD: 'Load',
    CLOSE: 'Close',
    REMOVE: 'Remove',
    SAVE: 'Save',
    RENAME: 'Rename',
    DELETE: 'Delete',
    API_REQUEST: 'API request',
    REQUIRED_PERMISSIONS: 'required permissions.',
    REQUIRED_VIEW_PERMISSIONS: 'Required permissions',
    REQUIRED_OPERATE_PERMISSIONS: 'Required permissions',
    CANCEL: 'Cancel',
    CONTINUE: 'Continue',
    DEFAULT_AWS_ACCOUNT_SUB_TEXT: 'No AWS credentials are available to create this configuration.',
    STEP_ONE: 'Option 1:',
    STEP_TWO: 'Option 2:',
    ERROR: 'Error:',
    NO_CRED: 'No Credentials.',
    CREATE_PERMISSION_ERROR: [
        'Workload Factory is unable to validate sufficient permissions. ',
        'View missing permissions.',
        'Redirect to ',
        'AWS CloudFormation',
        ' to complete this task.'
    ],
    MISSING_BLOCKED_PERMISSIONS: [
        'Creation failed due to ',
        'missing & blocked permissions. ',
        ' Go to the AWS console to set permissions correctly.',
        'Optionally, ensure that you have the ',
        ' to create your deployment with AWS CloudFormation.',
        'Click Redirect to CloudFormation via Codebox to complete the task.',
        'required permissions'
    ],
    CREATE_PERMISSION_ERROR_CHATBOT:
        'Workload Factory is unable to validate sufficient permissions. Redirect to AWS CloudFormation through the Codebox on the right to complete this task. Ensure that you have the CloudFormation ',
    NAVIGATE_TO: ['Go to the', ' and add the required credentials.'],
    STEP_TWO_TEXT: [
        'Continue without credentials and create AWS resources using the Codebox on the right.',
        'Ensure that you have the required permissions to complete this task within AWS CloudFormation.',
        'View the required permissions.'
    ],
    OPTION_ONE: 'To generate a CloudFormation stack for deployment from AWS, minimum permissions are required.',
    OPTION_TWO: 'To deploy the configuration from NetApp Console, full permissions are required.',
    OPTION_TWO_WF: 'To deploy the configuration from Workload factory, full permissions are required.',
    FOR_MORE_INFO: 'Learn more about the',
    HOW_TO_ADD_AWS_CRED: 'Learn how to add AWS credentials.',
    AWS_ACCOUNT_SUB_TEXT:
        'Select credentials that grant NetApp Console the permissions required to deploy and manage Microsoft SQL Server and FSx for ONTAP.',
    AWS_ACCOUNT_SUB_TEXT_WF:
        'Select credentials that grant Workload factory the permissions required to deploy and manage Microsoft SQL Server and FSx for ONTAP.',
    AWS_ACCOUNT_SUB_TEXT_AUTOMATE:
        'Use NetApp Console in automate mode by selecting credentials that grant NetApp Console the AWS permissions required to deploy and manage resources in your AWS account.',
    AWS_ACCOUNT_SUB_TEXT_READ:
        'Use NetApp Console in read mode by selecting AWS credentials that provide the read permissions required to generate a CloudFormation template. You can then use the template from the AWS CloudFormation console to provision stacks.',
    AWS_ACCOUNT_SUB_TEXT_WF_AUTOMATE:
        'Use any other Workload Factory policy to generate a CloudFormation template, which can later be used from the AWS CloudFormation console to provision stacks.',
    AWS_ACCOUNT_SUB_TEXT_WF_READ:
        'Use the Workload Factory database host creation policy by selecting credentials that grant Workload Factory the AWS permissions required to deploy and manage resources in your AWS account.',
    AWS_ACCOUNT_DEFAULT_LIST_TWO:
        'If you prefer not to enter your account credentials, continue to fill the form below, and we will produce the applicable CloudFormation code that you can copy and operate by yourself.',
    AWS_DEFAULT_LIST_FIRST:
        "page and add the credentials that you'd like to use, so we could create the DB for you. Deployment will take about 2 hours.",
    GO_TO_THE: 'Go to the',
    REQUIRED_PERMISSION_LINK: 'required permissions and how to add AWS credentials',
    REQUIRED_PERMISSION_LINK_ACCOUNTS: 'View required permissions.',
    REQUIRED_PERMISSION_LINK_ACCOUNTS2: 'View the required permissions.',
    MS_SQL_REQUIRED: 'Microsoft SQL on FSxN for ONTAP required permissions',
    CREDENTIALS: 'Credentials page',
    CREDENTIAL: 'Credentials.',
    CREDENTIAL_WITHOUT_DOT: 'Credentials',
    ADD_NEW_CREDENTIALS: 'To add a new credentials, go to the ',
    MULTI_AZ_CHECK_MESSAGE:
        'The selected VPC is not optimized. You should choose a VPC with subnets in 2 availability zones so that each cluster node will be in a dedicated availability zone.',
    QUERY_ERROR: 'Error',
    DB_CREATE_SUCCESS_MSG: 'DB creation is in progress',
    PERMISSION_REQUIRED: 'Permissions required',
    CLOUDFORMATION_TEMPLATE_URL: ['CloudFormation template ', 'URL'],
    // Constants for Security group
    USE_AN_EXISTING_SECURITY: 'Use an existing security group',
    GENERATED_SECURITY_GROUP: 'Create a new security group',
    EXISTING_SECURITY_GROUP: 'Existing security group',
    // Constants for Op system
    WIN_SERVER_2016: 'Windows server 2016',
    WIN_SERVER_2019: 'Windows server 2019',
    WIN_SERVER_2022: 'Windows server 2022',
    WIN_SERVER_2016_VERSION: '2016',
    WIN_SERVER_2019_VERSION: '2019',
    WIN_SERVER_2022_VERSION: '2022',
    OP_SYS_TEXT: 'Choose the operating system on which to install SQL Server.',
    // Constants for DB Deployment
    FAILOVER_CLUSTER: 'Failover cluster instance (FCI)',
    FAILOVER_CLUSTER_TEXT: 'Deploy your SQL Server Failover Cluster Instance across multiple Availability Zones',
    PGSQL_STANDALONE: 'Deploy your PostgreSQL Server on a single node',
    PGSQL_HA:
        'Deploy your PostgreSQL Server across multiple Availability Zones for high availability and data redundancy',
    STANDALONE_INSTANCE: 'Standalone instance',
    HIGH_AVAILABILITY: 'High availability (HA)',
    SINGLE_INSTANCE: 'Single Instance',
    SINGLE_INSTANCE_TEXT: 'Deploy your SQL Server on a single node.',
    // Constants for DB Edition
    SQL_SERVER_STANDARD: 'Standard',
    SQL_SERVER_STANDARD_EDITION: 'SQL Server Standard Edition',
    SQL_SERVER_STANDARD_EDITION_TEXT:
        'Core data management and business intelligence capabilities for mission-critical applications and mixed workloads.',
    SQL_SERVER_WEB: 'Web',
    SQL_SERVER_WEB_EDITION: 'SQL Server Web Edition',
    SQL_SERVER_WEB_EDITION_TEXT:
        "In accordance with Microsoft's licensing policies, it can only be used to support public and Internet-accessible webpages, websites, web applications, and web services.",
    SQL_SERVER_ENTERPRISE: 'Enterprise',
    SQL_SERVER_ENTERPRiSE_EDITION: 'SQL Server Enterprise Edition',
    SQL_SERVER_ENTERPRiSE_EDITION_TEXT:
        'Comprehensive high-end capabilities for mission-critical applications with demanding database workloads and business intelligence requirements.',
    // Constants for DB version
    SQL_SERVER_2019: 'SQL Server 2019',
    SQL_SERVER_2016: 'SQL Server 2016',
    SQL_SERVER_2022: 'SQL Server 2022',
    SQL_SERVER_2019_VERSION: '2019',
    SQL_SERVER_2016_VERSION: '2016',
    SQL_SERVER_2022_VERSION: '2022',
    VERSION: 'Version',
    // Constants for License accordion
    LICENSE_TEXT:
        'Use an AWS AMI (which includes a license) or bring your own SQL license (BYOL) through a custom AMI.',
    LICENSE_INCLUDED_AMI: 'License included AMI',
    VIEW_THE_REQ: 'View the requirements',
    LICENSE_ID: 'SQL Server AMI',
    USE_CUSTOM_AMI: 'Use custom AMI',
    CUSTOM_AMI: 'Custom AMI',
    AMI_ID: 'AMI',
    SELECT_AMI_ID: 'Select AMI',
    SELECT_AMI_NAME: 'Select AMI Name',
    FILTER_SQL_SERVER_AMI: 'Filter SQL Server AMI',
    SELECT_SQL_SERVER_AMI: 'Select SQL Server AMI',
    // Constants for DB name accordion
    DATABASE_INSTANCE_NAME: 'Database cluster name',
    DB_NAME_TOOLTIP:
        'The cluster name must be 15 characters or less. The first character can be a letter (a-z or A-Z) or a number (0-9). Subsequent characters can be a letter, number, or hyphen (-).',
    DB_NAME_TOOLTIP1: 'The cluster name must be 15 characters or less',
    DB_NAME_TOOLTIP1_PGSQL: 'The server name must be 15 characters or less',
    DB_NAME_TOOLTIP2: 'The first character can be a letter (a-z or A-Z) or a number (0-9)',
    DB_NAME_TOOLTIP3: 'Subsequent characters can be a letter, number, or hyphen (-)',
    KEY_PAIR_NAME: 'Key pair',
    // Constants for Storage capacity
    CAPACITY: 'Capacity',
    UNIT: 'Unit',
    CAPACITY_PGSQL_TOOLTIP:
        'Specify the PostgreSQL data drive size only. The provisioning for log drive, and other FSx for ONTAP file system volumes (including LUNs), will be performed according to NetApp best practices for PostgreSQL configuration. You can change the recommended defaults to meet your requirements.',
    CAPACITY_TOOLTIP:
        'Specify the SQL data drive size only. The provisioning for log drive, tempdb, and other FSx for ONTAP file system volumes (including LUNs), will be performed according to NetApp best practices for SQL configuration. You can change the recommended defaults to meet your requirements.',
    ERROR_CAPACITY: 'Supported capacity should be between 120 GiB to 86 TiB.',
    // Provisioned IOPS
    AUTOMATIC: 'Automatic',
    USER_PROVISIONED: 'User-provisioned',
    IOPS_VALUE: 'IOPS value',
    AUTOMATIC_IOPS: '3 IOPS per GiB of SSD storage will be created.',
    PLACEHOLDER_PROVISIONED: '3072 - 160000 IOPS',
    THROUGHPUT: 'Throughput',
    // SIMPLE NOTIFICATION SERVICES
    SNS: 'Enable the Simple Notification Service (SNS) for this configuration',
    SNS_TEXT: 'Enter an SNS topic for Microsoft SQL Server to send notifications and alerts.',
    SNS_TEXT_PGSQL: 'Enter an SNS topic for PostgreSQL Server to send notifications and alerts.',
    ARN: 'ARN',
    // Cloud watch
    CLOUD_WATCH_MONITORING: 'CloudWatch monitoring',
    RESOURCE_ROLLBACK: 'Resource rollback',
    CLOUD_WATCH_TEXT:
        'Set up monitors and automated insights for this SQL deployment using CloudWatch Application Insights.',
    CLOUD_WATCH_TEXT_PGSQL:
        'Set up monitors and automated insights for this PostgreSQL deployment using CloudWatch Application Insights.',
    // Resource Text
    RESOURCE_TEXT_ONE: 'When a deployment fails, your provisioned resources will not be rolled back by default.',
    RESOURCE_TEXT_TWO:
        'The provisioned resources will be deleted when you delete your deployment from the AWS console.',
    // FSX Accordion
    CREATE_NEW_FSXN: 'Create new FSx for ONTAP',
    CREATE_NEW_FSXN_SYSTEM: 'Create new file system',
    SELECT_EXISTING_FSX: 'Select an existing FSx for ONTAP ',
    FSXN_NAME: 'FSx for ONTAP name',
    USER_NAME: 'User name',
    FSX_PASSWORD: 'FSx for ONTAP password',
    NOTICE: 'Notice:',
    NOTICE_FSX_TEXT: 'New filesystem provisioning adds another 30 minutes to the total installation time.',
    PASSWORD_FSX_1: 'The password must be at least eight characters long.',
    PASSWORD_FSX_2: 'The password must contain at least one letter and one number.',
    PASSWORD_FSX_3: 'The password cannot contain the user name.',
    PASSWORD_FSX_4: 'The password cannot contain the word "admin".',
    // Active Directory
    DOMAIN_NAME: 'Domain name',
    DNS_ADDRESS: 'DNS address',
    AD_TEXT:
        'The directory in which you want to allow authorized users to authenticate with this SQL Server instance using Windows Authentication. Windows Server Failover Cluster requires that all servers be joined to the same Active Directory domain. Ensure that you have connection between the Active Directory and the VPC.',
    PASSWORD: 'Password',
    // Region VPC accordion
    REGION: 'Region',
    REGION_VPC_TEXT:
        'Choose the Virtual private cloud (VPC). The VPC defines the virtual  networking  environment for this DB instance.',
    SELECT_EXISTING_VPC: 'Select an existing VPC',
    CREATE_NEW_VPC: 'Create new VPC',
    REGION_VPC: 'Region & VPC',
    VPC: 'VPC',
    // Availability zone
    AZ_TEXT:
        'Select an Availability Zone and subnet for each node. Ensure that each of the selected private subnets have outbound connectivity enabled. The subnet for node 1 must be in the primary Availability Zone for the FSx for ONTAP file system.',
    CLUSTER_CONFIG_NODE_1: 'Cluster configuration - Node 1:',
    CLUSTER_CONFIG_NODE_2: 'Cluster configuration - Node 2:',
    CLUSTER_CONFIG_PGSQL: 'Node configuration - Select subnet:',
    AZ_Zone: 'Availability zone',
    SUBNET: 'Subnet',
    // DB credential
    DATABASE_CREDENTIAL_TEXT:
        'Create a new service account for SQL server or use existing service account credentials in the Active Directory',
    DATABASE_CREDENTIAL_TEXT_PGSQL: 'Provide password to the postgres user',
    USERNAME_TOOLTIP:
        'The user name must contain at least 5 alphanumeric characters. The user name can\'t be "admin" or "administrator".',
    USERNAME_TOOLTIP1: 'The user name must contain at least 5 alphanumeric characters.',
    USERNAME_TOOLTIP2: 'The user name can\'t be "admin" or "administrator".',
    USERNAME_TOOLTIP3: 'The user name must be enclosed in quotation marks. For example:',
    USERNAME_EXAMPLE: '"johnDoe"',
    USERNAME_TOOLTIP4: 'The user name must contain at most 20 alphanumeric characters.',

    PASSWORD_MIN_LENGTH_8: 'Password must be atleast 8 characters long',
    PASSWORD_CRED_1:
        'The password must be between 8 and 128 characters in length and contain characters from three of the following four categories: ',
    PASSWORD_CRED_LI_1: 'Uppercase letters (A-Z)',
    PASSWORD_CRED_LI_2: 'Lowercase letters (a-z)',
    PASSWORD_CRED_LI_3: 'Base 10 digits (0 through 9)',
    PASSWORD_CRED_LI_4:
        'Non-alphanumeric characters such as: exclamation point (!), dollar sign ($), number sign (#), or percent (%)',
    PASSWORD_CRED_4: "The password can't contain the user name.",
    // Encryption
    ENCRYPTION_TEXT:
        'Select the key to encrypt this database storage (FSx for ONTAP). You can select from master keys in your account or enter the ARN of a key from a different account.',
    ENCRYPTION_SELECT_FROM_ACCOUNT: 'Select a key from your account',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT: 'Select a key from another account',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT_TEXT:
        'If needed, you can select a customer-managed key from another AWS account by entering the Amazon Resource Name (ARN) of that key. You can find the ARN from the Amazon Key Management Service console. Key ARN starts with ‘arn:aws:kms’ or ‘arn:aws-us-gov:kms’.',
    ENCRYPTION_TEXT_FIELD: 'Encryption key ARN',
    ENCRYPTION_SELECT_FROM_OTHER_ACCOUNT_SUB_TEXT:
        'AWS is responsible for data encryption and decryption operations. Key management is handled by AWS Key Management Service.',
    CUSTOMER_MASTER_KEY_NAME: 'Key name',
    KEY_ID: 'Key ID',
    EXPIRATION_DATE: 'Expiration date',
    ORIGIN: 'Origin',
    ONLY_ENABLED_KEYS: 'Only enabled keys are displayed.',
    TAGS_HEADING_MSG: 'You can add upto 40 tags',
    ADD_NEW_TAG: '+ Add new tag',
    TAG_KEY: 'Tag key',
    TAG_VALUE: 'Tag value',
    TAG_KEY_PLACEHOLDER: 'Up to 127 characters',
    TAG_VALUE_PLACEHOLDER: 'Up to 255 characters',
    SELECT_ANY_ACCOUNT: 'Select your AWS credentials first',
    SELECT_ANY_VPC: 'This field will be enabled after you select a region and VPC.',
    SELECT_AZ: 'Select the Availability Zones first',
    CLOUD_FORMATION_URL_TEXT: 'The CloudFormation URL can be loaded using the',
    PASSWORD_ERROR_CHECK: 'Check password criteria',
    CREATE_INFO_MESSAGE: [
        'Microsoft SQL Server and FSxN for ONTAP deployment ',
        'with stack name ',
        ' has been triggered. You can track the progress using the ',
        'Timeline',
        '. Estimated time: Up to 2 hours. We will notify you as soon as the deployment is completed.'
    ],
    CREATE_INFO_MESSAGE_WLM: [
        'Microsoft SQL Server and FSxN for ONTAP deployment has been triggered. Track progress using ',
        'Job monitoring',
        '. Estimated time: Up to 2 hours.'
    ],
    CREATE_PGSQL_INFO_MESSAGE_WLM: [
        'PostgreSQL and FSxN for ONTAP deployment has been triggered. Track progress using ',
        'Job monitoring',
        '. Estimated time: Up to 2 hours.'
    ],
    IP_DOMAIN: 'SQL Server IP address or domain name',
    AUTHENTICATION_TYPE: 'Authentication type',
    DISCOVER_FORM_HEADING:
        'Enter connection details for Microsoft SQL Server that is accessible from the NetApp Console Agent',
    IS_REQUIRED_MSG: ' is required',
    DATABASES_SUMMARY: 'Databases summary',
    DATABASES: 'Databases',
    TOTAL_VOLUME: 'Total',
    TOTAL_SIZE: 'Total size',
    INFORMATION: 'Information',
    RESOURCE_DISTRIBUTION: 'Resources Distribution',
    TIMELINE: 'Timeline',
    REMOVE_DATABASE_HOST: 'Remove database host',
    REMOVE_CONFIG_TEXT: 'Are you sure you want to remove database host?',
    REMOVE_FROM_WORKSPACE: 'Remove from workspace',
    TABLES_SUMMARY: 'Tables summary',
    TABLES: 'Tables',
    // Estimation cost
    ESTIMATED_COST: 'Estimated cost',
    ESTIMATED_SUBTEXT: 'Estimate of charges incurred to deploy the following resources.',
    RESOURCES: 'Resources',
    AMOUNT_IN_USD: 'Amount in USD (monthly)',
    COMPUTE: 'Compute',
    INSTANCE_TYPE_EC: 'Instance type',
    QUANTITY: 'Quantity',
    STORAGE: 'Storage',
    OTHER: 'Other',
    TYPE: 'Type',
    VOLUME_TYPE: 'Volume type',
    ELASTIC_BLOCK_STORE: 'Elastic Block Store (EBS)',
    SIZE: 'Size',
    ESTIMATED_MONTHLY_COST: 'Estimated monthly cost',
    EC_NOTE:
        'This is only an estimate of AWS costs to deploy additional resources and does not include any taxes or discounts that may apply. Actual fees depend on many factors, including actual usage of AWS services.',
    MS_SQL_CPU_USED: 'CPU used by Microsoft SQL Server',
    CPU_REM: 'CPU available and used by other processes',
    MS_SQL_MEMORY_USED: 'Memory used by Microsoft SQL Server',
    MEMORY_REM: 'Memory available and used by other processes',
    MS_SQL_DISK_USED: 'Storage used by Microsoft SQL Server',
    DISK_REM: 'Storage available and used by other processes',
    OVERVIEW: 'Overview',
    MSSQL: 'Microsoft SQL Server',
    REMOVE_DIALOG_CONTENT_FIRST_PART: (weType: string) => `You are about to remove the ${weType} working environment`,
    REMOVE_DIALOG_CONTENT_SECOND_PART: 'from workspace.',
    REMOVE_DIALOG_NOTICE: (weType: string) => `This will not affect the ${weType} instance.`,
    // PREVIEW DEFAULT
    PREVIEW_DEFAULT_TEXT:
        'Easy create sets the following configurations to their default values, some of which can be changed later. If you want to change any of these settings now, use',
    PD_HEADER_TEXT: 'View the default configuration created by the system',
    PREVIEW_DEFAULT: 'Preview default',
    EDITABLE_AFTER: 'Editable after creation',
    DEFAULT: 'Default',
    CONFIGURATION: 'Configuration',
    PD_DISABLED: 'Disabled',
    ENABLED: 'Enabled',
    YES: 'Yes',
    PD_AUTO_CREATE: 'Automatically create based on user selection',
    NO: 'No',
    PD_CREATE_SECURITY: 'Create a security group for the user',
    PD_UPGRADED_MANUALLY: 'Yes (can be upgraded manually)',
    FIRST_IN_THE_LIST: 'First in the list',
    ACTIONS: 'Actions',
    DEPLOY: 'Deploy',
    MIGRATE: 'Migrate',
    CLONE: 'Clone',
    PROTECT: 'Protect',
    AWS_INTEGRATION: 'AWS Integration',
    CONFIG_CLOUDWATCH: 'Configure CloudWatch monitoring',
    PROTECT_AWS_BACKUP: 'Protect with AWS Backup',
    CONNECT_TO_AWS_SAGE: 'Connect to AWS SageMaker',
    CONNECT_TO_AD: 'Connect to Active Directory',
    THROUGHPUT_DISABLE_TEXT:
        "Throughput capacity is already set on the FSx for ONTAP file system. You can't change this value.",
    IOPS_DISABLE_TEXT: "Provisioned IOPS is already set on the FSx for ONTAP file system. You can't change this value.",
    KMS_DISABLE_TEXT: "Encryption Key is already set on the FSx for ONTAP file system. You can't change this value.",
    NOT_AVAILABLE: 'n/a',
    UNAVAILABLE: 'Unavailable',
    NO_ANALYSIS_PERFORMED: 'No analysis performed',
    // Constants for workload factory database host
    DATABASE_HOST: 'Database host',
    DATABASE_HOSTS: 'Database hosts',
    HOSTS: 'Hosts',
    PROTECTED: 'Protected',
    NOT_PROTECTED: 'Not protected',
    PROTECTION_TOOLTIP: [' out of ', ' databases are protected'],
    AWS_BACKUP: 'AWS backup',
    FSX_ONTAP_SNAPSHOTS: 'FSx for ONTAP Snapshots',
    SQL_SERVER_BACKUP: 'Native SQL server backup',
    CRR_ENABLED: 'Cross-region replication enabled',
    PROTECTED_BY: 'Protected By',
    DEPLOY_NEW_DATABASE: 'Deploy database host',
    DISCOVER: 'Discover',
    MIGRATE_DB: 'Migrate',
    CLONE_DB: 'Clone',
    PROTECT_DB: 'Protect',
    // database host headers
    DATABASE_HOST_NAME: 'Database host name',
    DB_HOST_PROTECTION: 'Protection',
    DB_HOST_PROTECTION_TYPE: 'Protection type',
    APPLICATION_CONSISTENT: 'Application-consistent',
    CRASH_CONSISTENT: 'Crash-consistent',
    DB_OVERVIEW_INFO: 'Information',
    DB_HOST_PERFORMANCE: 'Performance',
    DB_HOST_STORAGE_SAVINGS: 'Storage savings',
    DB_SS_TT_1:
        'Shows cumulative storage savings across Primary storage achieved as a result of Dedupe, Compression, Snapshots and thin Clones. ',
    DB_SS_TT_2: 'Calculation is based on unique FSx for ONTAP instance',
    DB_HOST_ESTIMATED_COST: 'Estimated cost',
    DB_HOST_ALLOCATED_CAPACITY: 'Allocated capacity',
    DB_HOST_INSTANCE_NAME: 'EC2 instance name',
    DB_HOST_INSTANCE_ID: 'EC2 instance ID',
    DB_HOST_INSTANCE: 'EC2 instance',
    DB_HOST_VPC: 'VPC',
    DB_HOST_AVAILABILITY: 'Availability',
    DB_HOST_TYPE: 'Type',
    DB_HOST_COLLATION: 'Collation',
    DB_HOST_DEPLOYMENT_MODEL: 'Deployment model',
    DB_HOST_REGION: 'Region',
    DB_HOST_FILE_SYSTEM_TYPE: 'Storage type',
    // Job Status constants
    JOB_STATUS: 'Job status',
    JOB_STATUS_DAYS: '(Last 30 days)',
    VIEW_JOB_MONITORING: 'View job monitoring',
    JOB_STATUS_COMPLETED: 'Completed',
    JOB_STATUS_FAILED: 'Failed',
    JOB_STATUS_RUNNING: 'Running',
    JOB_STATUS_JOBS: ' Jobs',
    JOBS_DISTRIBUTION: 'Jobs distribution',
    JOB_DISTRIBUTION: 'Job distribution',
    // Database Host constants
    DATABASE_HOST_STATUS: 'Database host status',
    DB_HOST_UP: 'Up',
    DB_HOST_DOWN: 'Down',
    DB_HOST_INITIALIZING: 'Initializing',
    DB_HOST_FAILED: 'Failed',
    // Database Host protection constants
    DATABASE_PROTECTION: ' Protected database distribution',
    DB_HOST_PROTECTED: 'Protected',
    DB_HOST_UNPROTECTED: 'Unprotected',
    PROTECTED_DB_DISTRIBUTION: 'Protected database distribution',
    SIDEBAR_LOAD_WIZARD: 'Load Wizard',
    PROTECTION_DATABASES: 'Hosts',
    PROTECTION_CHART: 'Protection',
    PROTECTION: 'protection',
    NUMBER_OF_EXECUTION: 'Number of Execution',
    TERRAFORM: 'Terraform',
    TERRAFORM_CODEBOX_TOOLTIP: 'The code includes only the root module. Download to access all modules.',
    READ: 'Read',
    WRITE: 'Write',
    STORAGE_PERFORMANCE: 'Storage performance',
    LATENCY: 'Latency',
    IOPS: 'IOPS',
    DOMAIN_NAME_INFO: 'Domain name:',
    DNS_ADDRESS_INFO: 'DNS address:',
    RESOURCE_UTILIZATION: 'Resource utilization',
    MEMORY: 'Memory',
    RESOURCES_DISTRIBUTION: 'Resource distribution',
    CPU: 'CPU',
    AWS_ACC_INFO: 'AWS account:',
    REGION_INFO: 'Region:',
    AZ_INFO_1: 'Availability Zone 1:',
    SUBNET_INFO_1: 'Subnet 1:',
    AZ_INFO_2: 'Availability Zone 2:',
    SUBNET_INFO_2: 'Subnet 2:',
    DEPLOYMENT_MODEL_INFO: 'Deployment model:',
    OS_INFO: 'Operating system:',
    EDITION_INFO: 'Edition:',
    VERSION_INFO: 'Version:',
    CLUSTER_COLLATION_NAME: 'Collation:',
    CLUSTER_NAME_INFO: 'Cluster name:',
    NODE_NAMES: 'Node names:',
    STATUS_INFO: 'Status:',
    CONNECTIONS_INFO: 'Connections:',
    DATE_CREATED: 'Date Created:',
    DB_INSTANCE_TYPE: 'DB Instance type:',
    FILE_SYS_NAME: 'File system name:',
    FILE_SYS_ID: 'File system ID:',
    FILE_SYS_TYPE: 'File system type:',
    FILE_SYS_STATUS: 'File system status:',
    STORAGE_CAPACITY_INFO: 'Storage capacity:',
    FILE_SYS_DP_TYPE: 'File system deployment type:',
    FSX_THROUGHPUT_TYPE: 'FSx Throughput capacity:',
    KEY_PAIR_NAME_INFO: 'Key pair name:',
    VPC_INFO: 'VPC:',
    TOPOLOGY: 'Topology',
    STATUS: 'Status',
    HOST_NAME: 'Host name',
    INSTANCE_NAME: 'Instance name',
    NO_OF_DBS: 'Number of databases',
    TOTAL_USED_CAPACITY: 'Total used capacity',
    SQL_VERSION: 'SQL version',
    RESOURCE_DEPLOYMENT_MODEL: 'Deployment model',
    RESOURCE_EDITION: 'Edition',
    TOTAL_ALLOCATED_CAPACITY: 'Total allocated capacity',
    ESTIMATED_COST_TOOLTIP:
        "Cost estimation provides an estimate of your AWS fees and doesn't include any taxes that might apply. Your actual fees depend on a variety of factors, including your actual usage of AWS services.",
    LEARN_HOW_ESTIMATED_COST: 'Learn how to improve cost accuracy',
    EC_HEADER: 'For more accurate results based on AWS billing and cost management, follow these steps:',
    STEP1: 'Step 1:',
    STEP1TEXT: 'Grant AWS billing and cost management data permissions.',
    STEP1POINT1: 'Sign in to the AWS Management Console and open the IAM service.',
    STEP1POINT2: 'Edit the policy for role and add AWS billing and cost management data permissions.',
    STEP1POINT3: 'User should quickly get the minimal needed billing permissions with an option to Copy.',
    STEP2: 'Step 2:',
    STEP2TEXT: 'Ensure the payer account activates the cost allocation tag.',
    STEP2POINT1: 'Open the AWS Billing and Cost Management console.',
    STEP2POINT2: 'In the navigation pane, choose ',
    STEP2POINT2CONTINUE: 'Cost allocation tags',
    STEP2POINT4: 'Select',
    STEP2POINT4ACTIVATE: 'Activate.',
    JOBS_STATUS_OVER_TIME: 'Job status over time',
    JOB_MONITORING: 'Job monitoring',
    POLICY_MANAGEMENT: 'Policy management',
    // Job Monitoring constants
    JM_COMPLETED: 'Completed',
    JM_IN_PROGRESS: 'In Progress',
    JM_FAILED: 'Failed',
    JM_WARNING: 'Completed with issues',
    NO_DATA: 'No data',
    JM_RUNNING: 'Running',
    JM_TYPE_DEPLOYMENT: 'Deployment',
    JM_TYPE_CREATE_RESOURCE: 'Create database',
    ADD_DATABASE: 'Add database',
    JM_TYPE_PREPARE_RESOURCE: 'Prepare resource',
    JM_TYPE_SANDBOX: 'Sandbox',
    JM_TYPE_ASSESSMENT: 'Assessment',
    JM_TYPE_OPTIMIZE: 'Well-architected',
    JM_TYPE_REGISTER_RESOURCE: 'Register resource',
    JM_DOWNLOAD_PROGRESS: 'Download in progress',
    JM_DOWNLOAD_SUCCESS: 'Jobs table was downloaded',
    DEMO_TITLE: 'Redirect to CloudFormation',
    DEMO_CONTENT: "When using a Demo account you won't be redirected to the AWS CloudFormation service.",
    FSXN_SVM_ERROR: [
        'Selected FSX has more than ',
        ' SVMs. Amazon FSx does not support having more than ',
        ' storage virtual machines for an ONTAP file system with ',
        ' MBps of throughput capacity.'
    ],
    FSXN_SECONDARY_SUBNET_ERROR:
        'The primary and secondary subnets of FSx for ONTAP file system does not reside in the selected availability zones.',
    FSXN_PRIMARY_SUBNET_ERROR:
        'The subnet for node 1 must be in the primary Availability Zone for the FSx for ONTAP file system.',
    FSXN_DEPLOYMENT_MODE_ERROR: 'Deployment mode not supported.',
    SINGLE_FSXN_DEPLOYMENT_MODE_ERROR: 'Single AZ 2 deployment type not supported.',
    MULTI_FSXN_DEPLOYMENT_MODE_ERROR: 'Multi AZ 2 deployment type not supported.',
    FSXN_NOT_AVAILABLE: 'FSx for ONTAP file system is not in available state.',
    TAB_DASHBOARD: 'Dashboard',
    TAB_INVENTORY: 'Inventory',
    TAB_JOB_MONITORING: 'Job monitoring',
    TAB_MANAGED_HOSTS: 'Managed hosts',
    TAB_UNAMANGED_HOSTS: 'Unmanaged hosts',
    TAB_UNIDENTIFIABLE_HOSTS: 'Unidentifiable hosts',
    DB_HOSTS_DISTRIBUTION: 'Database hosts distribution',
    DETECTED_DB_HOSTS_DISTRIBUTION: 'Detected database hosts distribution',
    INSTANCES_DISTRIBUTION: 'Instances distribution',
    DETECTED_HOSTS: 'Detected hosts',
    UNIDENTIFIABLE_HOSTS: 'Unidentifiable hosts',
    HOSTS_PENDING_DETECTION: 'Hosts pending detection',
    UNIDENTIFIABLE_HOST: 'Unidentifiable host',
    UNMANAGED_HOSTS: 'Unmanaged hosts',
    MANAGED_BY_WLF: 'Managed by Workload Factory',
    MANAGED_HOSTS_HEADING: 'Managed hosts',
    MANAGED_HOST_HEADING: 'Managed host',
    // Create USER DB
    FILE_SETTINGS_FIRST_TEXT: 'Select a new drive letter or an existing drive letter for the data file.',
    FILE_SETTINGS_SECOND_TEXT:
        'If you select a new drive letter, we recommend selecting a new drive letter for the log file.',
    CREATE_DB_NAME_TOOLTIP: [
        'SQL databases should have names that are no more than 123 characters long.',
        'Names can only contain alphanumeric characters, including letters, numbers and underscrores.',
        'Names should not be Transact-SQL reserved words.'
    ],
    CREATE_SANDBOX_NAME_TOOLTIP: [
        'SQL databases should have names that are no more than 27 characters long.',
        'Names can only contain alphanumeric characters, including letters, numbers and underscrores.',
        'Names should not be Transact-SQL reserved words.',
        'Data file path and Log file path should not be more than 255 characters long.'
    ],
    CREATE_DB_DATA_FILE_NAME_TOOLTIP: [
        'Data file name should have names that are no more than 128 characters long.',
        'Names can only contain alphanumeric characters, including letters, numbers and underscrores.'
    ],
    CREATE_DB_LOG_FILE_NAME_TOOLTIP: [
        'Log file name should have names that are no more than 128 characters long.',
        'Names can only contain alphanumeric characters, including letters, numbers and underscrores.'
    ],
    DB_NAME_ERROR_CHECK: 'Check database name criteria',
    DB_DATA_NAME_ERROR_CHECK: 'Check data file name criteria',
    DB_LOG_NAME_ERROR_CHECK: 'Check log file name criteria',
    DB_ADVANCED_CREATE: 'Advanced create',
    DB_QUICK_CREATE: 'Quick create',
    QUICK_DB_CREATE_CONTENT: [
        'Recommended for large databases. Quick create mode selects an optimal configuration for you.',
        'Quick create enhances database performance by allocating new drive letters for you and segregating the user database layout into distinct volumes and LUNs per data and log files.'
    ],
    ADVANCED_DB_CREATE_CONTENT:
        'Recommended for small to medium databases. With Advanced create mode, you set your storage layout configuration to well-architect performance by configuring new and existing drive letter options for data and log files.',
    FILE_SIZE_TEXT: [
        'Data and log file sizes have a minimum value of 1 GiB.',
        'The recommended log file size (default) is 25% of the data file size. The default log file size value is editable.'
    ],
    CREATE_USER_DB_TITLE: 'Create user database',
    DB_CREATE_HOST: 'Host:',
    DB_CREATE_INSTANCE: 'Instance:',
    CREATE: 'Create',
    CREATE_TEMPLATE: 'Create template',
    ONPREM_CREATE_TEMPLATE_DISABLE:
        'This configuration is not supported by our deployment wizard. Manual deployment is possible.',
    DB_CREATE_NOTIFICATION: ['Creation of ', ' in ', ' is in progress. Track progress in '],
    SANDBOX_ACTIONS_NOTIFICATIONS: {
        IN_PROGRESS: {
            delete: ['Deletion of ', ' sandbox is in progress. Track progress in '],
            rebaseline: ['Re-baselining of ', ' sandbox is in progress. Track progress in '],
            refresh: ['Refreshing of ', ' sandbox is in progress. Track progress in '],
            split: ['Splitting of ', ' sandbox is in progress. Track progress in '],
            integrityCheck: ['Integrity check of ', ' sandbox is in progress. Track progress in ']
        },
        SUCCESS: {
            delete: ['Sandbox database ', ' deleted successfully.'],
            rebaseline: [
                'Sandbox of database ',
                ' re-baselined successfully. Sandbox returned to its original version.'
            ],
            refresh: ['Sandbox of database ', ' refreshed successfully.'],
            split: ['Sandbox database ', ' split successfully.'],
            integrityCheck: ['Integrity check of ', ' completed successfully']
        },
        FAILED: {
            delete: ['Sandbox database ', ' failed to delete.'],
            rebaseline: ['Re-baseline of sandbox of database ', ' failed.'],
            refresh: ['Sandbox of database ', ' refresh failed.'],
            split: ['Sandbox database ', ' failed to split.'],
            integrityCheck: ['Integrity check of ', ' failed']
        }
    },
    DATABASE_INFORMATION: 'Database information',
    FILE_SETTINGS: 'File settings',
    DB_CREATE_DATABASE_NAME: 'Database name',
    COLLATION: 'Collation',
    DB_CREATE_FILES_SIZE: 'File sizes',
    DB_CREATE_FILE_SETTINGS_MODE: 'File settings mode',
    DB_CREATE_FILE_NAMES_AND_PATH: 'File names & path',
    DATA_FILE_SIZE: 'Data file size:',
    LOG_FILE_SIZE: 'Log file size:',
    DATA_FILE_NAME: 'Data file name',
    LOG_FILE_NAME: 'Log file name',
    DATA_FILE: 'Data file',
    LOG_FILE: 'Log file',
    DATA_FILE_PATH: 'Data file path:',
    LOG_FILE_PATH: 'Log file path:',
    SELECT_DRIVE_LETTER: 'Select drive letter',
    CLONED_COPIES_MAX_LIMIT: 'Number of cloned copies should be less than or equals to 10',
    CHANGE_RATE_MAX_LIMIT: 'Monthly change rate should be less than or equals to 100',
    LOG_SIZE_MIN_ERROR: 'Log file size should be 1 GiB or more.',
    NO_DATA_SIZE_ERROR: 'Data file size should be 1 GiB or more.',
    LOG_SIZE_ERROR: 'Log file size should be less than data file size.',
    DATA_SIZE_MIN_ERROR: 'Minimum space required to create the file is not available in the drive',
    DATA_SIZE_ERROR: 'The valid range is 1 GiB - ',
    DRIVE_LETTER_CREATE_ERROR: 'Action required: Drive letters are missing. Use Advanced Create mode to select drives.',
    COLLATION_ERROR: 'Action required: Select collation',
    SELECT_COLLATION: 'Select a collation',
    DRIVE_LETTER_QUICK_CREATE_ERROR:
        'Insufficient drive letters available on system to create new drives. Use Advanced Create mode to reuse existing drives.',
    RESOURCE_ROLLBACK_TOOLTIP:
        'When a deployment fails, your provisioned resources will not be rolled back by default. The provisioned resources will be deleted when you delete your deployment from the AWS console.',
    DATA_SIZE_TOOLTIP: ['Host ', ' data size range is '],
    NON_CLUSTERED_DRIVE: 'Non clustered drive or drive not part of SQL server',
    NON_NETAPP_DRIVE: 'Not a NetApp drive',
    CF_COPIED: 'CloudFormation copied successfully.',
    CF_DOWNLOAD: 'CloudFormation downloaded successfully.',
    CF_NOTICE: 'Notice: access to the YAML configuration file expires after 7 days.',
    TERRAFORM_DOWNLOAD: 'Terraform downloaded successfully',
    TERRAFORM_NOTICE: 'Notice: Access to the zip file expires after 7 days.',
    SSM_NO_CONNECTION_MSG: 'Can’t connect to your instance. See',
    SSM_NO_CONNECTION_LINK: 'Troubleshooting SSM agent',
    SSM_NO_CONNECTION: ['Workload Factory can’t connect to this host.', 'See troubleshooting SSM agent'],
    SEE_SSM_LINK: 'see troubleshooting SSM agent',
    OFFLINE_COMPONENT_TEXT_1: 'Unable to display host data',
    OFFLINE_COMPONENT_TEXT_2: 'Workload Factory cannot connect to this host.',
    SAME_NEW_DRIVE_ERROR: 'Data and log file drive letters should be different for new drives.',
    FSX_FOR_ONTAP: 'FSx for ONTAP',
    EBS: 'EBS',
    FSX_FOR_WINDOWS: 'FSx for Windows',
    SINGLE_AZ: 'Single AZ',
    MULTI_AZ: 'Multi AZ',
    // Const for unidentifiable data
    DETECT_HOST: 'Detect host',
    DETECT_INSTANCE: 'Authenticate Instance',
    MANAGE_HOST: 'Manage host',
    DETECT_HOST_STEPS: ['Step 1 / 2', 'Step 2 / 2'],
    FAILED_TO_DETECT_HOST: 'Failed to authenticate host',
    DETECT_FAILED_WITH_NO_STORAGE:
        'Unable to identify attached storage. For SQL user authentication, reload the inventory page and try to manage again.',
    DONE: 'Done',
    DETECT: 'Detect',
    SSM_CONNECTIVITY: 'SSM connectivity',
    SSM_ONLINE: 'Online',
    SSM_CONNECTION_LOST: 'Connection lost',
    DETECT_HOST_DESC: 'Detect and manage Microsoft SQL Server deployed on EC2 instance ',
    DETECT_INSTANCE_DESC: 'Detect and register instance ',
    DETECT_ONLY_INSTANCE: 'Detect instance',
    DETECT_MSSQL_HEADING: 'Microsoft SQL Server',
    DETECT_MSSQL_USERNAME: 'Microsoft SQL Server user name',
    DETECT_MSSQL_PASSWORD: 'Microsoft SQL Server password',
    DETECT_FSX_HEADING: 'FSx for ONTAP system',
    DETECT_FSX_USERNAME: 'ONTAP user name',
    DETECT_FSX_PASSWORD: 'ONTAP password',
    DETECTED_HOST_INFO: 'Detected host information',
    DETECTED_INSTANCE_INFO: 'Detected instance information',
    DETECT_HOSTNAME: 'Host name',
    DETECT_INSTANCE_NAME: 'Instance name',
    DETECT_STORAGE_TYPE: 'Storage type',
    DETECT_NO_OF_DB: 'Number of databases',
    DETECT_SQL_VERSION: 'SQL version',
    DETECT_DEPLOYMENT_MODEL: 'Deployment model',
    DETECT_EDITION: 'Edition',
    EBS_DETECT_SUCCESS_MSG: [
        'Host ',
        ' detected successfully.',
        'The host is now listed in the ',
        ' Unmanaged hosts ',
        ' tab.'
    ],
    EBS_INSTANCE_DETECT_SUCCESS_MSG: ['Instance ', ' detected successfully.'],
    FSX_DETECT_SUCCESS_MSG: [
        'Detected host management',
        'Would you like to manage the detected host via Workload Factory?'
    ],
    FSX_INSTANCE_DETECT_SUCCESS_MSG: [
        'Detected instance management',
        'Would you like to manage the detected instance via Workload Factory?'
    ],
    FSX_AFTER_DETECT_OPTIONS: ['Yes, Manage host via Workload Factory.', 'No, move host to the Unmanaged hosts tab.'],
    FSX_INSTANCE_AFTER_DETECT_OPTIONS: ['Yes, Register instance via Workload Factory.', 'No.'],
    HOST_MOVED_SUCCESS: [
        'Host ',
        ' successfully detected and moved to the ',
        ' Unmanaged hosts ',
        ' Managed hosts ',
        'tab.'
    ],
    INSTANCE_MANAGE_REQUEST: ['Your request to register the ', ' is in progress.'],
    MULTI_INSTANCE_MANAGE_REQUEST: ['Your request to register ', ' is in progress.'],

    INSTANCE_SUCCESS_DETECTED: ['Instance ', ' successfully detected.'],
    INSTANCE_SUCCESS_DETECTED_FAILED_MANAGED: ['Instance ', ' successfully detected but failed to become managed. '],
    HOST_MANAGED_MOVED_SUCCESS: ['Host ', ' successfully moved to the ', ' Managed hosts ', 'tab.'],
    HOST_MOVED_FAILED: ['Host ', ' failed to become a managed host. ', 'For more details view ', ' Job Monitoring.'],
    HOST_MOVED_INFO: [
        'Host ',
        ' successfully moved to unmanaged host but failed to become a managed host. ',
        'For more details view ',
        ' Job Monitoring.'
    ],
    PREPARE_HOST_INFO_TAB2: [
        'Host ',
        ' is unable to become a managed host because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_DETECTED_INSTANCE_INFO: [
        'Instance ',
        ' state is changed to unmanaged but is unable to become a registered instance because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_DETECTED_INSTANCES_INFO: [
        'Instances ',
        'state has been changed to unmanaged but are unable to become registered instances because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_INSTANCE_INFO: [
        'Instance ',
        ' is unable to become a managed instance because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_INSTANCES_INFO: [
        'Instances ',
        'are unable to become registered instances because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_BULK_INSTANCES_INFO: [
        'Few instances ',
        'are unable to become registered instances because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    PREPARE_HOST_INFO_TAB3: [
        'Host ',
        ' is now an unmanaged host. It failed to become a managed host because dependent PowerShell modules are not installed. Workload Factory will install the modules and then you can try again. Check ',
        'Job monitoring',
        ' to see when the modules have been installed.'
    ],
    FCI: 'FCI',
    AOAG: 'Always on availability group',
    HA: 'High availability',
    STANDALONE: 'Standalone',
    SERVICE: 'Service',
    PERMISSIONS: 'Permissions',
    ERROR_PERMISSION: 'Error',
    COPY_ALL_UNSUPPORTED_PERMS: 'Copy all unsupported permissions',
    BLOCKED_BY_ORG: 'Blocked by organization:',
    BLOCKED_BY_PERMISSION_BOUNDARY: 'Blocked',
    MISSING_PERMISSION: 'Missing',
    MISSING_AND_BLOCKED_PERMISSIONS: 'Missing & blocked permissions',
    UNSUPPORTED_PERMISSIONS: 'Missing permissions',
    DATA_VOLUME: 'Data volume',
    DATA_SIZE: 'Data volume size',
    LOG_VOLUME: 'Log volume',
    LOG_SIZE: 'Log volume size',
    TEMPDB_VOLUME: 'Tempdb volume',
    TEMPDB_SIZE: 'Tempdb volume size',
    QUORUM_VOLUME: 'Quorum volume',
    QUORUM_SIZE: 'Quorum volume size',
    BUFFER_SIZE: 'Headroom',
    DATA_REPLICA_VOLUME: 'Data replica volume',
    LOG_REPLICA_VOLUME: 'Log replica volume',
    MIN_FSX_CAPACITY_MESSAGE: 'The minimum total SSD capacity of an FSx for ONTAP file system is 1,024 GiB.',
    VPC_MESSAGE:
        'Ensure your VPC has connectivity to other AWS services (SQS, FSx, EC2, CloudWatch, CloudFormation, SSM) via VPC endpoints and S3 gateway endpoint. If not, endpoints will be created automatically during deployment.',
    SQL_SERVER_NOT_RUNNING: 'SQL server instance is not running.',
    SQL_SERVER_MANAGED: 'SQL server instance is currently managed.',
    SSM_CONNECTION_DOWN: 'SSM is not connected',
    STORAGE_NOT_PRESENT: 'Storage could not be identified',
    // Sandbox constants
    SANDBOX: 'Sandbox',
    SANDBOXES: 'Sandboxes',
    SANDBOX_HEADER_CONTENT:
        'Sandbox is an on-demand, isolated database environment that can be used for testing, integration, diagnostics, and training, without affecting production data. It streamlines the development lifecycle while ensuring data integrity and security.',
    CREATE_NEW_SANDBOX: 'Create new sandbox',
    SANDBOX_DEFINITION: 'Sandbox definitions',
    DONT_SHOW_AGAIN: "Don't show again",
    SANDBOX_DB_NAME: 'Database name',
    SANDBOX_DB_HOST_NAME: 'Database host name',
    SANDBOX_DB_INSTANCE_NAME: 'Database instance name',
    SANDBOX_SOURCE_DB_NAME: 'Source database name',
    SANDBOX_SOURCE_DB_HOST_NAME: 'Source database host name',
    SANDBOX_SOURCE_DB_INSTANCE_NAME: 'Source database instance name',
    SANDBOX_LAST_UPDATED: 'Last updated',
    DATABASE_SOURCE: 'Database source',
    Database_TARGET: 'Database target',
    AGE: 'Age',
    SANDBOX_TAG: 'Tag',
    SB_STATUS: 'Status',
    SANDBOX_SOURCE_DATABASES: 'Source databases',
    SANDBOX_STORAGE_SAVINGS: 'Storage savings',
    SAVINGS: 'Savings',
    SANDBOX_CONSUMED_STORAGE: 'Consumed storage',
    SANDBOX_SAVINGS: 'Sandboxes savings',
    SANDBOX_CONSUMED_SAVING: 'Consumed savings',
    SANDBOX_FCI_NOT_SUPPORTED: 'FCI sandbox creation not supported',
    SANDBOX_SMB_PROTOCOL_NOT_SUPPORTED: 'Sandbox creation not supported for SQL server using SMB protocol',
    DISTRIBUTION_BY_TAG: 'Sandboxes distribution by tag',
    DEVELOPMENT: 'Development',
    QA: 'QA',
    INTEGRATION: 'Integration',
    TRAINING: 'Training',
    ANALYTICS: 'Analytics',
    SANDBOX_OTHER: 'Other',
    SANDBOXES_DISTRIBUTION_BY_AGE: 'Sandboxes distribution by age',
    ONE_THIRTY_DAYS: '0-30 days',
    THIRTY_SIXTY_DAYS: '31-60 days',
    SIXTY_PLUS_DAYS: '61+ days',
    CREATE_SANDBOX: 'Create sandbox',
    TARGET_HOST: 'Target database host',
    TARGET_INSTANCE: 'Target database instance',
    TARGET_DATABASES: 'Target database',
    TARGET_DATABASE_NOTICE:
        'Notice: The target host must be in the same VPC and have the same FSx for ONTAP file system as the source host.',
    TARGET_DATABASE_NOTICE_V2:
        'Notice: The target instance must be in the same VPC and have the same FSx for ONTAP file system as the source instance.',
    SOURCE_HOST: 'Source database host',
    SOURCE_INSTANCE: 'Source database instance',
    SOURCE_DATABASE: 'Source database',
    MOUNT_NOTICE:
        'Notice: When cloning a SQL database that has multiple data and/or log files, Workload Factory clones all files under the auto-assigned or defined drive letter.',
    AUTO_ASSIGN_MOUNT_POINT: 'Auto-assign mount point',
    DEFINE_MOUNT_POINT_PATH: 'Define mount point path',
    VOLUME_MOUNT_POINT_UNDER_PATH: 'Volume mount point under path',
    SQL_SERVER_COLLATION: 'SQL Server collation',
    DEFINE_TAG: 'Define tag',
    HEADER_CREDENTIAL: 'Credential',
    HEADER_ACCOUNT_ID: 'Account ID',
    // ES volume summary keys
    ES_DETAILS: 'Details',
    ES_TOTAL_VOLUMES: 'Total volumes',
    ES_TOTAL_STORAGE_AMOUNT: 'Total storage amount',
    ES_TOTAL_PROVISIONED_IOPS: 'Total provisioned IOPS',
    ES_TOTAL_THROUGHPUT_MBPS: 'Total throughput MB/s',
    // Explore savings
    IOPS_DISABLE_TOOLTIP: "IOPS doesn't apply to this disc type volumes.",
    THROUGHPUT_DISABLE_TOOLTIP: "Throughput doesn't apply to this disc type volumes.",
    ES_SNAPSHOT_FREQUENCY: 'Snapshot frequency',
    ES_NO_SNAPSHOT_STORAGE: 'No snapshot storage',
    ES_CLONE_REFRESH_FREQUENCY: 'Clone refresh frequency',
    ES_TABLE_TITLE: 'Microsoft SQL Server hosts on Elastic Block Store',
    ES_TABLE_FSXW_TITLE: 'Microsoft SQL Server hosts on FSx for Windows',
    ES_TABLE_TITLE_SINGLE: 'Microsoft SQL Server host on Elastic Block Store',
    ES_TABLE_FSXW_TITLE_SINGLE: 'Microsoft SQL Server host on FSx for Windows',
    ES_SERVER_NAME: 'Server name',
    ES_TYPE: 'Type',
    ES_MSSQL_SERVER: 'Microsoft SQL Server on FSx for ONTAP',
    ES_MSSQL_EBS: 'Microsoft SQL Server on EBS',
    ES_MSSQL_FSXW: 'Microsoft SQL Server on FSx for Windows',
    ES_COST_BREAKDOWN: 'Cost breakdown - Monthly charge',
    ES_SAVINGS_SELECTION_TEXT: 'Provide clone and snapshot values to calculate the cost savings.',
    NUMBER_OF_CLONED_COPIES: 'Number of cloned copies',
    MONTHLY_CHANGE_RATE: 'Monthly change rate (%)',
    MONTHLY_DATA_CHANGE_RATE: 'Monthly data change rate (%)',
    RECOMMENDED_INSTANCE_TYPE: 'Recommended instance type',
    RECOMMENDED_INSTANCE_TYPE_INFO:
        'We base instance type recommendations on Amazon CloudWatch metrics (CPU, bandwidth, network, and more) taken over the last 14 days and AWS Compute Optimizer. If instances are over-provisioned, we recommend an instance type that may meet your needs better.',
    MISSING_PERMISSIONS_NOTICE: 'Improve cost accuracy.',
    RECOMMENDATIONS_UNAVAILABLE_NOTICE: 'Recommendations are unavailable.',
    RECOMMENDATIONS_UNAVAILABLE_TOOLTIP:
        'Recommendations are unavailable because of insufficient metrics or the analysis is still in progress.',
    LEARN_HOW: 'Learn how',
    LEARN_HOW_DIALOG: {
        TITLE: 'Improve compute cost accuracy',
        ASSESSMENT_TITLE: 'Improve compute assessment',
        ASSESSMENT_HEADER_TEXT:
            'For getting recommendations on Compute rightsizing based on AWS cloud watch metrics and Compute Optimizer, follow these steps.',
        HEADER_TEXT:
            'For more accurate results based on AWS cloud watch metrics and Compute Optimizer, follow these steps.',
        STEP1_HEADER: 'Grant AWS cloud watch and compute optimizer permissions.',
        STEP1_POINT1: 'Sign in to the AWS Management Console and open the IAM service.',
        STEP1_POINT2:
            'Edit the policy for the IAM role. Copy and add the following AWS CloudWatch and Compute Optimizer permissions.',
        PERMISSIONS: {
            Version: '2012-10-17',
            Statement: [
                { Effect: 'Allow', Action: 'compute-optimizer:GetEnrollmentStatus', Resource: '*' },
                { Effect: 'Allow', Action: 'compute-optimizer:PutRecommendationPreferences', Resource: '*' },
                { Effect: 'Allow', Action: 'compute-optimizer:GetEffectiveRecommendationPreferences', Resource: '*' },
                { Effect: 'Allow', Action: 'compute-optimizer:GetEC2InstanceRecommendations', Resource: '*' },
                { Effect: 'Allow', Action: 'autoscaling:DescribeAutoScalingGroups', Resource: '*' },
                { Effect: 'Allow', Action: 'autoscaling:DescribeAutoScalingInstances', Resource: '*' }
            ]
        },
        STEP2_HEADER: 'Opt the billable AWS account in to AWS Compute Optimizer.',
        STEP2_TITLE: 'Ensure the payer account opt in to the compute optimizer.',
        STEP2_POINT1: 'Open the AWS Compute Optimizer console ',
        STEP2_POINT1_LINK: 'https://console.aws.amazon.com/compute-optimizer/',
        STEP2_POINT2: 'Choose Get started.',
        STEP2_POINT3: 'On the Account setup page, review the Getting started and Setting up your account sections.',
        STEP2_POINT4:
            'The following options : Only this account/ All accounts within organization are displayed if the account that you are signed in to is the management account of your organization. Choose one before continuing to the next step.',
        STEP2_POINT5: 'Choose Opt in.',
        FOOTER_TEXT: 'The changes take effect within 24 hours.'
    },
    FINDINGS: {
        OPTIMIZED: 'Optimized',
        NOT_OPTIMIZED: 'Not optimized',
        OVER_PROVISIONED: 'Over-provisioned',
        INSUFFICIENT_DATA: 'n/a',
        UNDER_PROVISIONED: 'Under-provisioned',
        INSUFFICIENT_PERMISSIONS: 'n/a'
    },
    INSTANCE_TYPE_FINDINGS_TOOLTIP:
        'Displays findings (over-provisioned, under-provisioned, or optimized) based on analysis of Amazon CloudWatch metrics (CPU, bandwidth, network, and more) of the current instance and on the current memory of the instance. No finding appears when Workload Factory has insufficient permissions or unavailable metrics.',
    EC2_SPECIFICATIONS: 'EC2 specifications',
    REFER_SNAPSHOTS: 'This field refer to clones and snapshots',
    VIEW_THE_CALCULATIONS: 'View the calculations',
    EXPORT_PDF: 'Export PDF',
    ES_COST_SAVINGS: 'Cost savings',
    ES_SAVINGS_PERCENTAGE: 'Percentage savings',
    ES_HEADING: 'Authenticated host cost analysis',
    ES_HEADING_ONPREM_LEFT_SIDE: 'Migrate your on-premises SQL Server environment',
    ES_HEADING_ONPREM_RIGHT_SIDE: 'Assessment steps',
    ES_MIGRATE_SERVER_ENV:
        'Workload Factory migration advisor simplify and automate SQL Server migration planning by providing you a detailed design for cloud deployment using Amazon FSx for NetApp ONTAP. The migration advisor also allows you to validate the value of the provided design via a detailed cost comparison to alternative configurations and to automate the provisioning of the recommended architecture according to best practices and vendor solution deployment guidelines.',
    ES_HEADER:
        'You can identify potential savings by automatically comparing your database workloads to SQL Server using FSx for ONTAP file systems. Choose a SQL Server host and explore savings.',
    ES_SAVINGS: 'Explore savings',
    POTENTIAL_SAVINGS: 'Potential savings',
    SQL_SERVER_HOSTS_EBS: 'SQL Server hosts on Elastic Block Store (EBS)',
    SQL_SERVER_HOSTS_FSXW: 'SQL Server hosts on FSx for Windows',
    MANUAL_EXLORE_SAVINGS: 'Custom configuration cost analysis',
    EXPLORE_SAVING_MANUALLY: 'Analyze custom configuration for Elastic Block Store (EBS)',
    EXPLORE_SAVING_MANUALLY_FSX: 'Analyze custom configuration for FSx for Windows File Server',
    MANUAL_EXPLORE_SAVINGS_CONTENT:
        'You can adjust SQL Server, infrastructure, and storage settings to analyze for potential savings between your environment and SQL Server using FSx for ONTAP.',
    INSTANCE_INFORMATION: 'Instance information:',
    ES_SAVE_CONFIG: 'Save configuration',
    ES_SAVE_CONFIG_DESC:
        'You can save this Microsoft SQL Server on AWS EC2 and FSx for ONTAP file system configuration and load the configuration later for a future deployment.',
    ES_SAVE_ERROR: 'This configuration can not be saved',
    MS_SQL_TWO_INSTANCES: 'Microsoft SQL Server EC2 instance - 2 instances',
    MS_SQL_SINGLE_INSTANCES: 'Microsoft SQL Server EC2 instance',
    SAVINGS_HEADER: 'Microsoft SQL Server on Amazon Elastic Block Store (EBS) configuration.',
    SAVINGS_HEADER_FSX: 'Microsoft SQL Server on FSx for Windows configuration',
    SAVINGS_ONPREM_HEADER: 'Microsoft SQL Server on-premises configuration',
    SAVINGS_MANUAL_TEXT:
        ' Select a Microsoft SQL Server on Amazon EC2 with EBS configuration so that we can compare your costs when using Microsoft SQL Server on FSx for ONTAP instead',
    SAVINGS_MANUAL_FSXW_TEXT:
        'Select Microsoft SQL Server, Amazon EC2, and Amazon FSx for Windows File Server settings to compare the cost of using Microsoft SQL Server on FSx for ONTAP instead.',
    ES_NUMBER_OF_INSTANCE: 'Number of SQL instances',
    ES_HOST_NAME: 'Host name',
    ES_NUMBER_OF_VOLS: 'Number of volumes',
    SUMMARY_TEXT: 'Summary of the selected volumes by volume type:',
    SELECTION_BASED_TEXT: 'Based on your selections, we recommend creating the following:',
    SELECTION_BASED_SECOND: 'Microsoft SQL Server on AWS EC2 using FSx for ONTAP file system',
    RECOMMENDED_ES_TITLE: 'Microsoft SQL Server on AWS EC2 using FSx for ONTAP',
    SAVINGS_CALCULATOR: 'Savings calculator',
    TOTAL_MONTHLY_COST: 'Total monthly cost',
    TO_VIEW_STORAGE: 'To view storage cost savings, enter your configuration.',
    CATEGORY_POINT_ONE: 'Microsoft SQL Server on FSx for ONTAP',
    CATEGORY_POINT_TWO: 'Microsoft SQL Server on Amazon Elastic Block Store (EBS)',
    FSXW_CATEGORY: 'Microsoft SQL Server on FSx for Windows File Server',
    WINDOW_FILE_SERVER_DETAILS: 'FSx for Windows File Server:',
    VIEW_CALC_TEXT:
        'Learn how we calculated the estimated cost of Microsoft SQL Server on FSx for ONTAP for your specific use case and the configuration that you selected.',
    VIEW_CALCS: 'View calculations',
    VIEW_CAL_SECONDARY_TEXT: 'All AWS prices mentioned in the calculations are AWS on-demand pricing.',
    COST_CALCULATION: 'Cost calculation',
    DEPLOY_RATE_EXCEEDED: 'An internal error occurred when attempting to deploy the database server, please try again.',
    TOOLTIP_MESSAGE_SNAPSHOT_FREQ:
        'No EBS snapshots authenticated. If you would like to compare the cost of EBS snapshots to FSx for ONTAP snapshots, update the snapshot frequency.',
    NOTICE_MESSAGE_COST_SAVINGS:
        'This configuration cannot benefit from savings. Please check the cost breakdown below for further analysis.',
    PDF_DOWNLOAD_SUCCESS: 'PDF file downloaded successfully.',
    REPORT_DOWNLOAD_SUCCESS: 'Report downloaded successfully',
    MANAGE_HOST_DISABLED: 'Supported only for the FSx for ONTAP storage type',
    EXPLORE_SAVINGS_DISABLED: 'Supported only for the EBS storage type',
    SMB_PROTOCOL_DISABLED: 'Action not supported on SQL server using SMB protocol',
    MONTHLY_CHANGE_RATE_TOOLTIP: 'The monthly change rate is the % of data that changes per month.',
    CUSTOM_AMI_DISABLE_MSG: 'Not applicable for Custom AMI',
    CLONE_TARGET_DB_LENGTH_VALIDATION: 'Target database should not exceed 128 characters',
    ROLLBACK_CHECKBOX: 'Select the snapshot you would like the database to Roll-back to',
    DELETING: 'Deleting',
    REBASELINE: 'Re-baseline',
    SPLIT: 'Splitting',
    INTEGRITY_CHECK: 'Integrity check',
    REBASELINE_DIALOG_TITLE: ['Are you sure you want to re-baseline ', ' sandbox for database '],
    REBASELINE_DIALOG_FIRST_BULLET:
        'This action will revert the sandbox to its original version at the time of creation.',
    REBASELINE_DIALOG_SECOND_BULLET: 'Any changes you made to the sandbox will be deleted.',
    REFRESH_DIALOG_TITLE: ['Are you sure you want to refresh ', ' sandbox for database'],
    SPLIT_DIALOG_TITLE: ['Are you sure you want to split this sandbox ', ' from the source database '],
    SPLIT_DIALOG_FIRST_BULLET: [
        'The split will create a new database from this sandbox that will occupy ',
        ' in storage.'
    ],
    SPLIT_DIALOG_SECOND_BULLET:
        'Once the split is complete, the new database will appear in the inventory and this sandbox will be deleted.',
    REFRESH_DIALOG_FIRST_BULLET:
        'This action will update the selected sandbox so that it is equivalent to the source database at the current moment or at a previous point in time.',
    REFRESH_DIALOG_SECOND_BULLET: 'Any changes you made to the sandbox will be deleted.',
    REFRESH_CURRENT_RADIO: 'Refresh to current time',
    REFRESH_SNAPSHOT_RADIO: 'Refresh to point in time',
    HOST_DOWN: 'Host is down.',
    SSM_DOWN: 'SSM is not connected.',
    PGSQL_CTA_NA: 'Coming soon',
    NON_MSSQL_BULK_CTA: 'Bulk manage is only supported for Microsoft SQL Server instances.',
    DATABASE_AVAILABLE_MSG: 'Databases are available for registered instances only.',
    // Otimization status n/a messages
    ONLINE_INSTANCE_ASSESS: 'Only online instances can be assessed.',
    ONLINE_INSTANCE_DISMISS: 'Analysis state can be updated for online instances.',
    NO_CONFIG_AVAILABLE: 'Configurations data not available.',
    NO_ASSESSMENT_DATA: 'assessment not available.',
    LOG_DRIVE_OVER_PROVISIONED_ERROR: 'Over provisioned log drive size can not be optimized',
    TEMPDB_DRIVE_OVER_PROVISIONED_ERROR: 'Over provisioned tempDB drive size can not be optimized',
    HEADROOM_OVER_PROVISIONED_ERROR: 'Over provisioned headroom can not be optimized',
    NOT_OPTIMIZED_SHARED_DRIVES:
        'Drive size optimization isn’t possible because data is on the same shared drive. You’ll need to change the storage layout before resizing the drive.',
    ASSESSMENT_FOR_MANAGE: 'Well-architected analysis is only supported for registered instances.',
    FSXN_OPTIMIZE_SUPPORTED:
        'Well-architected analysis is only available for Microsoft SQL Server instances with FSx for ONTAP file system storage.',
    ASSESSMENT_FOR_UNDETECTED_FSXN: 'Well-architected is only supported for registered instances.',
    ASSESSMENT_STORAGE_TYPE_UNKNOWN:
        'Well-architected analysis is only supported for authenticated and registered FSx for ONTAP instances.',
    ASSESSMENT_AOAG_DETECTED: 'Well-architected analysis is only supported for registered instances.',
    ASSESSMENT_AOAG_UNDETECTED:
        'Well-architected analysis is only supported for authenticated and registered instances.',
    INVENTORY_LOADING_DISABLED: 'Inventory data loading',
    VIRTUAL_MOUNT_POINT_INFO_TOOLTIP:
        'Creates a partition access path folder containing the new database files in the selected drive. Use this option when you run out of drive letters or to consolidate files under existing drives with segregation at storage.',
    FSXN_MANAGE_SUPPORTED:
        'Only Microsoft SQL Server instances with FSx for ONTAP file system storage can be registered.',
    FSXN_MANAGE_SUPPORTED_ORACLE: 'Only Oracle databases with FSx for ONTAP file system storage can be registered.',
    MANAGE_DISABLE_FOR_UNDETECTED:
        'This instance is currently unauthenticated. To manage the instance, expand the database host name, and then select "authenticate" from the menu.',
    NO_UNMANAGED_TO_MANAGE:
        'All SQL Server instances on this host are either registered or unauthenticated. To manage the instance, click on view instance, and then select "authenticate" from the menu.',
    AOAG_MANAGE_DISABLE: 'Register instance is not supported for Always on availability group deployment model.',
    ALL_MANAGED_TEXT:
        'All SQL Server instances on this host are currently registered. To explore instance actions or deregister the instance, click on view instance, and click the menu.',
    ALL_FSXN_MANAGED_TEXT:
        'All FSx for ONTAP SQL Server instances on this host are currently registered. To explore instance actions or deregister the instance, click on view instance, and click the menu.',
    ALL_UNDETECT_TEXT:
        'All SQL Server instances on this host are currently unauthenticated. To manage the instance, click on view instance, and then select "detect" from the menu.',
    ALL_ES_UNDETECTED_ROWS:
        'All SQL Server instances on this host are currently unauthenticated. To explore savings on this instance first click on view instance, and then select "detect" from the menu.',
    ALL_ES_FSXW_AOAG_ROWS:
        'Explore Savings for FSx for Windows File Server is not supported for Always on availability group deployment model.',
    NON_SSD_FSXW_MSG:
        'Explore Savings for FSx for Windows File Server is only supported for SSD file system storage type.',
    MANAGED_SUPPORT_FOR_EBS_FSXW:
        'Register instance is not supported for EBS and FSx for Windows File Server storage type.',
    MIXED_STORAGE_ES_MSG: 'Explore Savings for mixed storage type is not supported.',
    MANAGE_INSTANCE_SUCCESS_MSG: ['The SQL Server instance ', ' has been successfully managed.'],
    MANAGE_INSTANCE_FAILED_MSG: [
        'The attempt to manage the SQL Server instance ',
        ' was unsuccessful. Please try again or contact support if the problem persists.'
    ],
    DETECT_MANAGE_INSTANCE_FAILED_MSG: [
        'The attempt to manage the SQL Server instance ',
        ' was unsuccessful. The instance state has been changed to unmanaged. Please try again or contact support if the problem persists.'
    ],
    MULTIPLE_INSTANCE_MANAGE_FAILED: [
        'The attempt to manage ',
        ' SQL Server instances was unsuccessful. Please try again or contact support if the problem persists.'
    ],
    MULTIPLE_INSTANCE_DETECT_MANAGE_FAILED: [
        'The attempt to manage ',
        ' SQL Server instances was unsuccessful. The instances state has been changed to deregister. Please try again or contact support if the problem persists.'
    ],
    MULTIPLE_INSTANCE_MANAGE_PARTIAL_SUCCESS: [' out of ', ' SQL Server instances have been successfully registered.'],
    MULTIPLE_INSTANCE_DETECT_MANAGE_PARTIAL_SUCCESS: [
        ' out of ',
        ' SQL Server instances have been successfully registered. The rest of the instances have been moved to deregister'
    ],
    MUTLI_INSTANCE_MANAGE_SUCCESS: [' SQL Server instances have been successfully registered.'],
    UNMANAGE_INSTANCE_SUCCESS_MSG: (instanceName: string) =>
        `Database instance ${instanceName} deregistered successfully.`,
    UNMANAGE_INSTANCE_FAILED_MSG: (instanceName: string) => `Database instance ${instanceName} failed to deregister.`,
    NOT_OPTIMIZED:
        "With FSx for ONTAP, you can change your SQL license from Enterprise to Standard because replication and other Enterprise features aren't in use.",
    // Explore savings view calculations related consts
    MS_EBS_CALCULATION: 'Microsoft SQL Server on EBS calculation',
    MS_FSXW_CALCULATION: 'Microsoft SQL on FSx for Windows File Server calculation',
    MS_ONTAP_CALCULATION: 'Microsoft SQL EC2 on FSx for ONTAP calculation',
    ES_CLONES: 'Clones',
    ES_SHADOW_COPY: 'Shadow copy',
    ES_EBS: 'Elastic Block Storage',
    ES_GP3_VOLUME_TYPE: 'GP3 volume type',
    ES_IO2_VOLUME_TYPE: 'io2 volume type',
    ES_IO1_VOLUME_TYPE: 'io1 volume type',
    ES_GP2_VOLUME_TYPE: 'GP2 volume type',
    ES_ST1_VOLUME_TYPE: 'St1 volume type',
    ES_EBS_TOTAL_COST: 'EBS total cost',
    ES_MSSQL_EC2_INSTANCES: 'Microsoft SQL EC2 Instances',
    ES_SNAPSHOTS: 'Snapshots',
    ES_SNAPSHOTS_DESC: 'Snapshot calculations are based on primary database volumes only and not on replicas.',
    ES_CLONES_DESC: 'Clone calculations are based on primary database volumes only and not on replicas.',
    ES_TOTAL_MONTHLY_COST: 'Total monthly cost',
    ES_FSXN_MULTI: 'Multi Availability Zone',
    ES_FSXN_SINGLE: 'Single Availability Zone',
    ES_FSXW_SINGLE: 'Single Availability Zone',
    ES_FSXW_MULTI: 'Multi Availability Zone',
    ES_FSXN_AZ_DESC:
        'FSx for ONTAP costs are based on primary database volumes only because these volumes and their replicas share a file system.',
    ES_EBS_DESC: 'Costs for EBS are based on all EC2 instances.',
    ES_SQL_EDITION_MULTI_TOOLTIP:
        'The value is determined by the highest SQL Server edition found in all SQL Server instances on the host.',
    ES_MULTI_FSX_DISABLE_MSG:
        'Deployment of Microsoft SQL Server over multiple FSx for ONTAP is currently not supported.',
    COMPUTE_RECOMMENDED_TOOLTIP:
        'The cost for compute of SQL over EBS is based on current instance type vs. cost of compute of SQL server over FSxN based on your selected instance type.',
    BYOL_TEXT: 'Monthly SQL BYOL costs($)',
    CREATE_SANDBOX_SOURCE_DB_NOT_ISCSI: 'Source database is not hosted on a NetApp iSCSI drive',
    COMING_SOON: 'Coming soon',
    NOTE_PONT_ONE: 'No disruption to your services are expected during this process.',
    NOTE_PONT_TWO:
        'Click continue to authorize Workload Factory to automatically perform these actions on your behalf.',
    OS_NOTE_POINT_ONE:
        'This process will require a temporary downtime of your SQL Server services. Perform necessary backups and notify affected users, to avoid any unintended downtime or data loss.',
    OS_NOTE_POINT_TWO:
        'Click Continue to authorize Workload Factory to automatically perform these actions on your behalf and acknowledge the required downtime.',
    NOTE: 'Note',
    SQL_COLLATION_NOTE:
        'If the selected collation is not supported, Workload Factory will automatically apply the default collation.',
    OPTIMIZATION_NOT_SUPPORTED: 'Coming soon',
    OPTIMIZATION_IN_PROGRESS: 'You will be able to fix after the current well-architected operation ends.',
    ONPREM_TOOLTIP:
        'The migration advisor SQL Server data collector is a lightweight data collection tool which is based on PowerShell. It gathers both SQL Server configuration and performance data for the most accurate plan design.',
    CLEAR_ALL: 'Clear all',
    COMPUTE_RIGHTSIZING: 'Compute rightsizing',
    RSS_CONFIGURATION: 'Network adapter settings',
    OPERATING_SYSTEM_PATCH: 'Operating system patch',
    MICROSOFT_SQL_PATCH: 'Microsoft SQL Server patch',
    MAXDOP_PATCH: 'MAXDOP',
    RIGHTSIZING_TOOLTIP:
        'Rightsizing recommendations are based on analysis from AWS Compute Optimizer which requires 14 days of metrics to provide accurate suggestions.',
    LICENSE_SQL_SERVER: 'License',
    APPLICATION: 'Application (SQL Server)',
    RESILIENCY: 'Resiliency',
    SCHEDULED_LOCAL_SNAPSHOT: 'Scheduled local snapshot',
    SCHEDULED_FSX_FOR_ONTAP_BACKUPS: 'Scheduled FSx for ONTAP backups',
    CRR: 'Cross-Region Replication (CRR)',
    MSSQL_HIGH_AVAILABILITY: 'Microsoft SQL Server High Availability',
    MTU: 'MTU alignment',
    CLONING: 'Cloning',
    CLONE_MANAGEMENT: 'Clone cleanup',
    MANAGE_INSTANCE_OPTIMIZATION_SCORE_TOOLTIP:
        'A well-architected score is available only for registered instances that have been analyzed and are online.',
    CLONE_MANAGEMENT_TAB1: 'Clones created in Workload factory (Sandboxes)',
    CLONE_MANAGEMENT_TAB2: 'Clones created outside Workload factory',
    MANAGED_INSTANCE_DISMISS_INFO:
        "You postponed or dismissed configuration analysis for some SQL Server instances. Configurations with postponed or dismissed analysis don't affect the well-architected score.",
    DISMISS_MIX_CASE_TOOLTIP: 'This configurations analysis is dismissed or postponed for some of the instances.',

    DISMISS_PAGE_MESSAGE:
        "Postpone the scan for 30 days or indefinitely. If you postpone the scan indefinitely, you'll need to manually restart the scan. You can postpone scans for specific instances or for all instances. Configurations that have postponed scans won't affect the total well-architected score.",
    MANAGE_ANALYSIS_STATE: 'Manage analysis state',
    REACTIVATE: 'Reactivate',
    POSTPONE_FOR_30_DAYS: 'Postpone for 30 days',
    DISMISS: 'Dismiss',
    ANALYSIS_STATE_CHANGE_SUCCESS: 'Updated analysis state.',
    ANALYSIS_STATE_CHANGE_FAILED: 'Failed to update analysis state.'
};

export const CODE_VIEWER = {
    REST_API: 'REST API',
    CLOUDFORMATION: 'CloudFormation',
    AWS_CLI: 'AWS CLI',
    VIEW_IN_AWS_CLOUD_FORMATION: 'View in AWS CloudFormation',
    DOWNLOAD_YAML: 'Download YAML file ',
    DOWNLOAD_ZIP: 'Download ZIP file',
    RECOMMENDED_DEV: 'Dev/Test',
    RECOMMENDED_PROD: 'Production',
    NO_DATA_MSG: 'No data',
    LOADING_CLOUD_FORMATION: 'Loading CloudFormation code',
    LOADING_TERRAFORM: 'Loading Terraform code',
    LOADING_REST_API: 'Loading REST API code',
    LOADING_AWS_CLI: 'Loading AWS CLI code',
    CODEBOX: 'Codebox',
    EXPAND: 'Expand',
    COLLAPSE: 'Collapse',
    RECOMMENDED_TEMPLATES_HEADING: 'Recommended templates - Microsoft SQL Server deployment',
    MY_TEMPLATES: 'My Templates',
    COPY: 'Copy',
    COPIED_TO_CLIPBOARD: 'Copied to clipboard',
    SIDEBAR_LOAD_WIZARD: 'Load wizard',
    MENU_LOAD_WIZARD: 'Load wizard',
    SHOW_CODE_AS: 'Show code as:',
    VIEW_CODE: 'View code',
    RENAME: 'Rename',
    DELETE: 'Delete',
    CREATION_DATE: 'Creation date:',
    DEPLOYMENT: 'Deployment:',
    CREATE_DATABASE: 'Create database',
    TERRAFORM: 'Terraform'
};

export const CHATBOT_FIELD_MAPPING: any = {
    credentialsId: 'credential id',
    region: 'region',
    vpcId: 'vpc',
    availabilityZone1: 'availability zone for primary node',
    availabilityZone2: 'availability zone for secondary node',
    vpcCidr: 'vpc cidr',
    privateSubnet1Id: 'subnet for primary node',
    routeTable1Id: 'route table for primary node',
    privateSubnet2Id: 'subnet for secondary node',
    routeTable2Id: 'route table for secondary node',
    workloadInstanceType: 'workload instance type',
    keyPairName: 'key pair name',
    sqlAmiId: 'sql ami id',
    adScenarioType: 'active directory scenario type',
    dnsIpaddress: 'dns ip address',
    domainDnsname: 'domain dns name',
    domainUsername: 'domain user name',
    domainPassword: 'domain password',
    fsxUsername: 'fsx user name',
    fsxPassword: 'fsx password',
    serviceAccountName: 'service account name',
    serviceAccountPassword: 'service account password',
    fsxDeploymentMode: 'fsx deployment mode',
    sqlDeploymentMode: 'sql deployment mode',
    databaseSize: 'database size',
    fsxVolThroughput: 'fsx volume throughput',
    fsxIOPS: 'fsx IOPS',
    ontapSgGroupId: 'ontap security group id',
    fsxType: 'fsx type',
    fsxFileSystemId: 'fsx file system id'
};

export const CHATBOT = {
    WELCOME_PAGE: {
        DB_WORKLOAD_EXPERT: 'Database workload expert',
        WELCOME_MSG:
            "Hello! I'm your virtual assistant for database lifecycle management. I can help you learn, deploy, and understand operations according to best practices. Enter a prompt or choose a suggestion to start a conversation.",
        RESUME_DEPLOYMENT_MSG:
            'Hi, we see that you already initiated values for deployment. How would you like to proceed?',
        ADVANCED_CREATE_MSG:
            'Deployment via chatbot is supported only with the easy create option, which provides some predefined configuration settings based on recommended best practices. Would you like to continue?',
        START_NEW_CHAT: 'Start new chat'
    },
    HEADER: {
        DISCLAIMER: 'Disclaimer: Chat responses are generated by AI and might contain errors or inaccuracies.',
        ABOUT_CHAT: 'About chat'
    }
};

export const GETWELL_DIALOG_CONTENT = {
    ACTION_SUMMARY: 'Action summary',
    USER_ACTION_REQUIRED: 'User action required',
    WHAT_WILL_HAPPEN: 'What will happen',
    DOWNTIME_WARNING: 'Downtime Warning',
    SELECT_INSTANCE: 'Select one of the recommended instance types.',
    COMPUTE_RS_AS_DESC:
        'Workload Factory is ready to migrate your SQL Server EC2 instance from the current instance type to the recommended instance type',
    COMPUTE_RS_WWH_DESC_FCI: [
        'Instance type change: Workload Factory will change the instance type for your Amazon EC2 instance from the current instance type to the recommended instance type on both SQL Server Always On Failover Cluster Instances (FCI) nodes.',
        'Failover and Failback: The migration will involve failing over and falling back from the primary node in your SQL Server Always On Failover Cluster Instances (FCI) to ensure a smooth transition.'
    ],
    COMPUTE_RS_WWH_DESC_STANDALONE:
        'Workload Factory will change the instance type for your Amazon EC2 instance from the current instance type to the recommended instance type.',
    COMPUTE_RS_DTW_NOTES_FCI: [
        'You can expect slower performance during failover and failback from the primary node in your SQL Server Always on FCI.',
        'Click Continue to authorize Workload Factory to automatically perform these actions on your behalf.'
    ],
    COMPUTE_RS_DTW_NOTES_STANDALONE: [
        'This process will require a temporary downtime of your SQL Server EC2 instance. Perform necessary backups and notify affected users, to avoid any unintended downtime or data loss.',
        'Click Continue to authorize Workload Factory to automatically perform these actions on your behalf and to acknowledge the required downtime.'
    ],
    COMPUTE_RS_LAST_POINT: [
        'Compute rightsizing fixing involves an instance type change and impacts all SQL Server instances and any other applications running on the host. Make sure that your applications are compatible with the new instance type. Refer to ',
        'AWS resize limitations',
        ' for limitations on changing instance types.'
    ]
};
