#prettier-ignore
---
AWSTemplateFormatVersion: 2010-09-09

Description: 'A CloudFormation template to use with an existing Amazon FSx for NetApp ONTAP file system. This template creates a storage virtual machine (SVM) with the required volumes for PGSQL Server workloads.'

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                  default: PGSQL Server volumes' configuration for Amazon FSx for NetApp ONTAP file system
              Parameters:
                  - DeploymentMode
                  - FSxFileSystemId
                  - FSxSvmName
                  - FSxDataVolumeName
                  - FSxDataVolumeSize
                  - FSxLogVolumeName
                  - FSxLogVolumeSize
        ParameterLabels:
            DeploymentMode:
                default: File system deployment mode
            FSxSvmName:
                default: Storage virtual machine name
            FSxDataVolumeName:
                default: Data volume name
            FSxDataVolumeSize:
                default: Data volume size
            FSxLogVolumeName:
                default: Log volume name
            FSxLogVolumeSize:
                default: Log volume size

Parameters:
    DeploymentMode:
        Description: The deployment mode for the FSx for ONTAP file system.
        Type: String
        Default: MULTI_AZ_1
        AllowedValues: [SINGLE_AZ_1, MULTI_AZ_1, SINGLE_AZ_2, MULTI_AZ_2]

    FSxFileSystemId:
        Description: ID of the FSx for ONTAP file system.
        Type: String

    FSxSvmName:
        Type: String
        MinLength: 1
        MaxLength: 47

    FSxDataVolumeName:
        Description: The name of the volume for PGSQL Server data.
        Type: String
        Default: wlmdb_fsx_data_volume

    FSxDataVolumeSize:
        Description: The size of the data volume in megabytes (MiB).
        Type: Number
        Default: 200

    FSxLogVolumeName:
        Description: The name of the volume for the PGSQL Server log.
        Type: String
        Default: wlmdb_fsx_log_volume

    FSxLogVolumeSize:
        Description: The size of the log volume in megabytes (MiB).
        Type: Number
        Default: 100

    SQLDeploymentMode:
        Description: PGSQL server deployment mode
        Type: String
        Default: 'ha'
        AllowedValues:
            - 'ha'
            - 'standalone'

Conditions:
    FSxIsMultiZoneDeployment: !Or
      - !Equals [!Ref DeploymentMode, 'MULTI_AZ_1']
      - !Equals [!Ref DeploymentMode, 'MULTI_AZ_2']
    IsHACluster: !Equals [!Ref 'SQLDeploymentMode', 'ha']

Resources:
    FSxSvmConfiguration:
        Type: AWS::FSx::StorageVirtualMachine
        Properties:
            Name: !Ref FSxSvmName
            FileSystemId: !Ref FSxFileSystemId
            RootVolumeSecurityStyle: UNIX

    FSxDataVolumeConfiguration:
        Type: AWS::FSx::Volume
        Properties:
            Name: !Ref FSxDataVolumeName
            VolumeType: ONTAP
            OntapConfiguration:
                SecurityStyle: UNIX
                SizeInMegabytes: !Ref FSxDataVolumeSize
                StorageVirtualMachineId: !Ref FSxSvmConfiguration
                JunctionPath: !Join ['', [/, !Ref FSxDataVolumeName]]
                OntapVolumeType: RW
                StorageEfficiencyEnabled: true
                TieringPolicy:
                    Name: SNAPSHOT_ONLY
                    CoolingPeriod: 7

    FSxLogVolumeConfiguration:
        Type: AWS::FSx::Volume
        Properties:
            Name: !Ref FSxLogVolumeName
            VolumeType: ONTAP
            OntapConfiguration:
                SecurityStyle: UNIX
                SizeInMegabytes: !Ref FSxLogVolumeSize
                StorageVirtualMachineId: !Ref FSxSvmConfiguration
                JunctionPath: !Join ['', [/, !Ref FSxLogVolumeName]]
                OntapVolumeType: RW
                StorageEfficiencyEnabled: true
                TieringPolicy:
                    Name: SNAPSHOT_ONLY
                    CoolingPeriod: 7

    FSxReplicaSvmConfiguration:
        Condition: IsHACluster
        Type: AWS::FSx::StorageVirtualMachine
        Properties:
            Name: !Sub "${FSxSvmName}_replica"
            FileSystemId: !Ref FSxFileSystemId
            RootVolumeSecurityStyle: UNIX

    FSxReplicaDataVolumeConfiguration:
        Condition: IsHACluster
        Type: AWS::FSx::Volume
        Properties:
            Name: !Sub "${FSxDataVolumeName}_replica"
            VolumeType: ONTAP
            OntapConfiguration:
                SecurityStyle: UNIX
                SizeInMegabytes: !Ref FSxDataVolumeSize
                StorageVirtualMachineId: !Ref FSxReplicaSvmConfiguration
                JunctionPath: !Join ['', [/, !Sub "${FSxDataVolumeName}_replica"]]
                OntapVolumeType: RW
                StorageEfficiencyEnabled: true
                TieringPolicy:
                    Name: SNAPSHOT_ONLY
                    CoolingPeriod: 7

    FSxReplicaLogVolumeConfiguration:
        Condition: IsHACluster
        Type: AWS::FSx::Volume
        Properties:
            Name: !Sub "${FSxLogVolumeName}_replica"
            VolumeType: ONTAP
            OntapConfiguration:
                SecurityStyle: UNIX
                SizeInMegabytes: !Ref FSxLogVolumeSize
                StorageVirtualMachineId: !Ref FSxReplicaSvmConfiguration
                JunctionPath: !Join ['', [/, !Sub "${FSxLogVolumeName}_replica"]]
                OntapVolumeType: RW
                StorageEfficiencyEnabled: true
                TieringPolicy:
                    Name: SNAPSHOT_ONLY
                    CoolingPeriod: 7

Outputs:
    FSxFileSystemId:
        Description: ID of the FSx for ONTAP file system
        Value: !Ref FSxFileSystemId
    FSxSvmId:
        Description: System generated ID of the storage virtual machine
        Value: !GetAtt FSxSvmConfiguration.StorageVirtualMachineId
        Export:
            Name: !Sub ${AWS::StackName}-FSxSvmId
    FSxSvmUuid:
        Description: System generated UUID of the storage virtual machine
        Value: !GetAtt FSxSvmConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxSvmUuid
    FSxDataVolumeLogicalId:
        Description: Logical ID of the FSx for ONTAP data volume
        Value: !Ref FSxDataVolumeConfiguration
        Export:
            Name: !Sub ${AWS::StackName}-FSxDataVolumeLogicalId
    FSxDataVolumeArn:
        Description: ARN of the FSx for ONTAP data volume
        Value: !GetAtt FSxDataVolumeConfiguration.ResourceARN
        Export:
            Name: !Sub ${AWS::StackName}-FSxDataVolumeArn
    FSxDataVolumeId:
        Description: System generated ID of volume
        Value: !GetAtt FSxDataVolumeConfiguration.VolumeId
        Export:
            Name: !Sub ${AWS::StackName}-FSxDataVolumeId
    FSxDataVolumeUuid:
        Description: System generated UUID of volume
        Value: !GetAtt FSxDataVolumeConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxDataVolumeUuid
    FSxLogVolumeLogicalId:
        Description: Logical ID of FSx for ONTAP log volume
        Value: !Ref FSxLogVolumeConfiguration
        Export:
            Name: !Sub ${AWS::StackName}-FSxLogVolumeLogicalId
    FSxLogVolumeArn:
        Description: ARN of FSx for ONTAP data volume
        Value: !GetAtt FSxLogVolumeConfiguration.ResourceARN
        Export:
            Name: !Sub ${AWS::StackName}-FSxLogVolumeArn
    FSxLogVolumeId:
        Description: System generated ID of volume
        Value: !GetAtt FSxLogVolumeConfiguration.VolumeId
        Export:
            Name: !Sub ${AWS::StackName}-FSxLogVolumeId
    FSxLogVolumeUuid:
        Description: System generated UUID of volume
        Value: !GetAtt FSxLogVolumeConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxLogVolumeUuid

    FSxReplicaSvmId:
        Condition: IsHACluster
        Description: System generated ID of the storage virtual machine
        Value: !GetAtt FSxReplicaSvmConfiguration.StorageVirtualMachineId
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaSvmId

    FSxReplicaSvmUuid:
        Condition: IsHACluster
        Description: System generated UUID of the storage virtual machine
        Value: !GetAtt FSxReplicaSvmConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaSvmUuid

    FSxReplicaDataVolumeLogicalId:
        Condition: IsHACluster
        Description: Logical ID of the FSx for ONTAP data volume
        Value: !Ref FSxReplicaDataVolumeConfiguration
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaDataVolumeLogicalId

    FSxReplicaDataVolumeArn:
        Condition: IsHACluster
        Description: ARN of the FSx for ONTAP data volume
        Value: !GetAtt FSxReplicaDataVolumeConfiguration.ResourceARN
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaDataVolumeArn

    FSxReplicaDataVolumeId:
        Condition: IsHACluster
        Description: System generated ID of volume
        Value: !GetAtt FSxReplicaDataVolumeConfiguration.VolumeId
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaDataVolumeId

    FSxReplicaDataVolumeUuid:
        Condition: IsHACluster
        Description: System generated UUID of volume
        Value: !GetAtt FSxReplicaDataVolumeConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaDataVolumeUuid

    FSxReplicaLogVolumeLogicalId:
        Condition: IsHACluster
        Description: Logical ID of FSx for ONTAP log volume
        Value: !Ref FSxReplicaLogVolumeConfiguration
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaLogVolumeLogicalId

    FSxReplicaLogVolumeArn:
        Condition: IsHACluster
        Description: ARN of FSx for ONTAP data volume
        Value: !GetAtt FSxReplicaLogVolumeConfiguration.ResourceARN
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaLogVolumeArn

    FSxReplicaLogVolumeId:
        Condition: IsHACluster
        Description: System generated ID of volume
        Value: !GetAtt FSxReplicaLogVolumeConfiguration.VolumeId
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaLogVolumeId

    FSxReplicaLogVolumeUuid:
        Condition: IsHACluster
        Description: System generated UUID of volume
        Value: !GetAtt FSxReplicaLogVolumeConfiguration.UUID
        Export:
            Name: !Sub ${AWS::StackName}-FSxReplicaLogVolumeUuid
