AWSTemplateFormatVersion: '2010-09-09'
Description: >
    This template deploys a Postgresql Server standalone instance using FSx for NetApp ONTAP in an existing VPC.
    This template creates EC2 instances and the required resources. You will be billed for AWS resources if you create a stack from this template.

Parameters:
    Ec2RoleName:
        Default: AmazonEC2RoleForLaunchWizard
        Description: EC2 instance role name.
        Type: String
    KeyPairName:
        Description: Name of an existing EC2 key pair. All instances will launch with this key pair.
        Type: AWS::EC2::KeyPair::KeyName
    PrivateSubnetID:
        Description: ID of private subnet in an Availability Zone 1 for the workload (For example, subnet-a0246dcd).
        Type: String
    VPCID:
        Description: ID of your existing VPC for deployment.
        Type: String
    VPCCIDR:
        AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
        ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
        Description: CIDR block for the VPC.
        Type: String
    WorkloadInstanceType:
        Description: EC2 instance type for the workload instances.
        Type: String
    NumberOfNodes:
        Description: The number of SQL Server nodes to create.
        Type: String
    RouteTableId:
        Description: Comma separated list of all route table IDs for SQL Server subnets.
        Type: String
    SQLSvmName:
        Description: Name of the storage virtual machine (SVM) that will host the SQL Server workload.
        Type: String
    FSxDataVolumeName:
        Description: The name of the volume for SQL Server data.
        Type: String
    FSxLogVolumeName:
        Description: The name of the volume for the SQL Server log.
        Type: String
    FSxFileSystemId:
        Description: ID for the FSx for ONTAP file system.
        Type: String
    FSXUsername:
        Description: Username for the FSx for ONTAP file system.
        Type: String
        Default: fsxadmin
    FSXPassword:
        Description: Password for the FSx for ONTAP file system.
        Type: String
        NoEcho: true
        Default: netapp1!
    FSxSVMId:
        Description: ID of the FSx Storage Virtual Machine
        Type: String
    FSxAggrName:
        Description: Aggregate FSx for ONTAP file system.
        Type: String
        Default: aggr1
    EBSVolumeSize:
        Description: Size of the EBS Volume in GiB.
        Type: String
    AMIID:
        Description: The AMI ID for the EC2 instances.
        Type: String
    SQLVersion:
        Description: The version of PostgreSQL to install.
        Type: String
    SqlFSxServerNetBIOSName:
        AllowedPattern: '[a-zA-Z0-9\-]+'
        Default: SqlFSx1
        Description: NetBIOS name of the SQL Server (up to 15 characters).
        MaxLength: '15'
        MinLength: '1'
        Type: String
    SqlServerName:
        Description: Name of the SQL Server.
        Type: String
    SQLServiceAccountPassword:
        Description: Password for the SQL service account.
        Type: String
        NoEcho: true
    ONTAPSecurityGroupID:
        Description: ID of the FSx for ONTAP security group.
        Type: String
    ParentStackName:
        Description: Stack name for the parent CloudFormation stack.
        Type: String

Resources:
    LaunchWizardSqlFSxProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
                - !Ref Ec2RoleName
            Path: /
    NetworkInterface:
        Type: AWS::EC2::NetworkInterface
        Properties:
            SecondaryPrivateIpAddressCount: 2
            SubnetId: !Ref 'PrivateSubnetID'
            GroupSet: !Split
                - ','
                - !Join
                    - ','
                    -   - !Ref 'WorkloadSecurityGroup'
                        - !Ref 'ONTAPSecurityGroupID'
            Tags:
                -   Key: Name
                    Value: !Ref 'SqlFSxServerNetBIOSName'
                -   Key: SQLServerName
                    Value: !Ref 'SqlServerName'
    SqlNode:
        Type: AWS::EC2::Instance
        CreationPolicy:
            ResourceSignal:
                Count: '1'
                Timeout: PT30M
        Metadata:
            AWS::CloudFormation::Init:
                configSets:
                    config:
                        - InstallSSMAgent
                        - CreateDeploymentFolders
                        - ConfigureCWLogs
                        - FetchResources
                        - ScriptSignatureVerificationandExtract
                        - Configure
                        - Finalize
                InstallSSMAgent:
                    commands:
                        a-install-ssm-agent:
                            command: !Sub
                                'sudo yum install -y https://s3.${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_amd64/amazon-ssm-agent.rpm'
                            waitAfterCompletion: '0'
                        b-install-cloudwatch-agent:
                            command: 'sudo yum install -y amazon-cloudwatch-agent.x86_64'
                            waitAfterCompletion: '0'
                CreateDeploymentFolders:
                    commands:
                        a-create-scripts-folder:
                            command: !Sub 'mkdir -p /home/ec2-user/cfn/scripts'
                            waitAfterCompletion: '0'
                        b-create-logs-folder:
                            command: !Sub 'sudo mkdir -p /var/log/netapp_wf'
                            waitAfterCompletion: '0'
                ConfigureCWLogs:
                    files:
                        /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json:
                            content: !Sub |
                                {
                                    "agent": {
                                        "metrics_collection_interval": 5,
                                        "run_as_user": "cwagent",
                                        "region": "${AWS::Region}"
                                    },
                                    "logs": {
                                        "logs_collected": {
                                            "files": {
                                                "collect_list": [
                                                    {
                                                        "file_path": "/var/log/cfn-*.log",
                                                        "log_group_name": "${ParentStackName}",
                                                        "log_stream_name": "{instance_id}"
                                                    },
                                                    {
                                                        "file_path": "/home/ec2-user/cfn/log",
                                                        "log_group_name": "${ParentStackName}",
                                                        "log_stream_name": "{instance_id}"
                                                    },
                                                    {
                                                        "file_path": "/var/log/netapp_wf/*.log",
                                                        "log_group_name": "${ParentStackName}",
                                                        "log_stream_name": "{instance_id}"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            mode: '000644'
                            owner: cwagent
                            group: cwagent
                    commands:
                        a-configure-cwlogs:
                            command: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
                            waitAfterCompletion: '0'
                FetchResources:
                    files:
                        /home/ec2-user/cfn/scripts/verify-signature.sh:
                            source: {{{ ScriptVerifySignature }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                        /home/ec2-user/cfn/scripts/unzip-archive.sh:
                            source: {{{ ScriptUnzipArchive }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                        /home/ec2-user/cfn/signig_files.zip:
                            source: {{{ ArtifactsSignatures }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                        /home/ec2-user/cfn/scripts/common.zip:
                            source: {{{ ScriptCommon }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                        /home/ec2-user/cfn/scripts/setup.zip:
                            source: {{{ ScriptSetup }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                        /home/ec2-user/cfn/fsx_certs.zip:
                            source: {{{ FsxCertificates }}}
                            mode: '000755'
                            owner: ec2-user
                            group: ec2-user
                ScriptSignatureVerificationandExtract:
                    commands:
                        a-change-to-sudo-user:
                            command: sudo su
                            waitAfterCompletion: 0
                        b-unpack-signatures:
                            command: /home/ec2-user/cfn/scripts/unzip-archive.sh -s /home/ec2-user/cfn/signig_files.zip -d /home/ec2-user/cfn
                            waitAfterCompletion: 0
                        c-verify-common-signature:
                            command: !Sub '/home/ec2-user/cfn/scripts/verify-signature.sh
                                    -f /home/ec2-user/cfn/scripts/common.zip
                                    -s /home/ec2-user/cfn/signig_files/common.zip.sig
                                    -p /home/ec2-user/cfn/signig_files/common.zip.pub
                                    -r SqlNode
                                    -n ${AWS::StackName}'
                            waitAfterCompletion: 0
                        d-unpack-common-scripts:
                            command: /home/ec2-user/cfn/scripts/unzip-archive.sh -s /home/ec2-user/cfn/scripts/common.zip -d /home/ec2-user/cfn/scripts
                            waitAfterCompletion: 0
                        e-verify-setup-signature:
                            command: !Sub '/home/ec2-user/cfn/scripts/verify-signature.sh
                                    -f /home/ec2-user/cfn/scripts/setup.zip
                                    -s /home/ec2-user/cfn/signig_files/setup.zip.sig 
                                    -p /home/ec2-user/cfn/signig_files/setup.zip.pub
                                    -r SqlNode
                                    -n ${AWS::StackName}'
                            waitAfterCompletion: 0
                        f-unpack-setup-scripts:
                            command: /home/ec2-user/cfn/scripts/unzip-archive.sh -s /home/ec2-user/cfn/scripts/setup.zip -d /home/ec2-user/cfn/scripts
                            waitAfterCompletion: 0
                        g-unpack-fsx-certificates:
                            command: /home/ec2-user/cfn/scripts/unzip-archive.sh -s /home/ec2-user/cfn/fsx_certs.zip -d /home/ec2-user/cfn
                            waitAfterCompletion: 0
                Configure:
                    commands:
                        a-configure-ontap:
                            command: !Sub 
                                - '/home/ec2-user/cfn/scripts/setup/configure-ontap.sh
                                    -f ${FSxFileSystemId}
                                    -r ${AWS::Region}
                                    -u ${FSXUsername}
                                    -p ${FSXPassword}
                                    -s ${FSxSVMId}
                                    -n ${SQLSvmName}
                                    -a ${FSxAggrName}
                                    -d ${FSxDataVolumeName}
                                    -l ${FSxLogVolumeName}'
                                -   FSxFileSystemId: !Ref 'FSxFileSystemId'
                                    FSXUsername: !Ref 'FSXUsername'
                                    FSXPassword: !Ref 'FSXPassword'
                                    FSxSVMId: !Ref 'FSxSVMId'
                                    SQLSvmName: !Ref 'SQLSvmName'
                                    FSxAggrName: !Ref 'FSxAggrName'
                                    FSxDataVolumeName: !Ref 'FSxDataVolumeName'
                                    FSxLogVolumeName: !Ref 'FSxLogVolumeName'
                            waitAfterCompletion: '0'
                        b-configure-pgsql:
                            command: !Sub
                                - '/home/ec2-user/cfn/scripts/setup/configure-pgsql.sh
                                    -d ${FSxDataVolumeName}
                                    -l ${FSxLogVolumeName}
                                    -v ${SQLVersion}
                                    -w ${SqlServiceAccountPassword}'
                                -   FSxDataVolumeName: !Ref 'FSxDataVolumeName'
                                    FSxLogVolumeName: !Ref 'FSxLogVolumeName'
                                    SQLVersion: !Ref 'SQLVersion'
                                    SqlServiceAccountPassword: !Ref 'SQLServiceAccountPassword'
                            waitAfterCompletion: '0'
                        c-rename-host:
                            command: !Sub
                                - '/home/ec2-user/cfn/scripts/common/rename-host.sh ${SqlServerName}'
                                - SqlServerName: !Ref 'SqlServerName'
                            waitAfterCompletion: '0'
                        c-restart-host:
                            command: sudo reboot
                            waitAfterCompletion: forever
                Finalize:
                    commands:
                        a-signal-resource:
                            command: !Sub 'cfn-signal -e $? --resource SqlNode --stack ${AWS::StackName} --region ${AWS::Region}'
                            waitAfterCompletion: '0'
                            
        Properties:
            IamInstanceProfile: !Ref LaunchWizardSqlFSxProfile
            InstanceType: !Ref WorkloadInstanceType
            ImageId: !Ref AMIID
            Tags:
                -   Key: Name
                    Value: !Ref 'SqlFSxServerNetBIOSName'
            BlockDeviceMappings:
                -   DeviceName: /dev/sda1
                    Ebs:
                        VolumeSize: !Ref EBSVolumeSize
                        VolumeType: gp3
            KeyName: !Ref KeyPairName
            NetworkInterfaces:
                -   NetworkInterfaceId: !Ref 'NetworkInterface'
                    DeviceIndex: 0
            UserData:
                'Fn::Base64':
                    !Sub |
                        #!/bin/bash -xe
                        token=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" -s http://169.254.169.254/latest/api/token)
                        echo "Token: $token"
                        instanceID=$(curl -H "X-aws-ec2-metadata-token: $token" -s http://169.254.169.254/latest/meta-data/instance-id)
                        echo "Instance ID: $instanceID"
                        FailureReason="CF endpoint is not reachable. Check your subnet outbound connectivity."
                        url=https://cloudformation.${AWS::Region}.amazonaws.com
                        StatusCode=$(curl -s -o /dev/null -w "%{http_code}" $url)
                        echo "Status code: $StatusCode"
                        if [ "$StatusCode" != "200" ]; then
                            echo $FailureReason
                            aws cloudformation signal-resource --stack ${AWS::StackName} --logical-resource-id SqlNode --status FAILURE --reason "$FailureReason" --region ${AWS::Region}
                            exit 1
                        else
                            echo "CF endpoint is reachable."
                            /opt/aws/bin/cfn-init -v -c config --stack ${AWS::StackName} --resource SqlNode --region ${AWS::Region}
                        fi
    WorkloadSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow access to the Workload instances
            VpcId: !Ref VPCID
            SecurityGroupIngress:
                -   IpProtocol: tcp
                    FromPort: 22
                    ToPort: 22
                    CidrIp: 10.0.0.0/16  # Replace with Subnet CIDR
                -   IpProtocol: tcp
                    FromPort: 2049
                    ToPort: 2049
                    CidrIp: 10.0.0.0/16  # Replace with Subnet CIDR
                -   IpProtocol: tcp
                    FromPort: 5432
                    ToPort: 5432
                    CidrIp:  10.0.0.0/16 # Replace with Subnet CIDR

Outputs:
    SqlNodeIp:
        Description: Private IP of Sql Instance
        Value: !GetAtt SqlNode.PrivateIp
    SqlNodeId:
        Description: Id of Sql Instance
        Value: !Ref SqlNode
