
#############################################################

# Deployment configs
namespace: "wlmdb"

# image (both init and app)
image:
  registry: "718273455463.dkr.ecr.us-east-1.amazonaws.com/wlmdb"

imagePullPolicy: IfNotPresent

# app resources
resources:
  limits:
    cpu: "2000m"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

resourcesaudit:
  limits:
    cpu: "150m"
    memory: "150Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

infraversion: development-ee05536-653
UseExternalIP: true

# monitoring
monitoring: true
promrelease: prometheus-operator
#############################################################

# App properties

## env vars to be mounted to pod
