-- AlterTable
ALTER TABLE `job` MODIFY `type` ENUM('DEPLOYMENT', 'CREATE_RESOURCE', 'PREPARE_RESOURCE', 'SANDBOX', 'ASSESSMENT', 'OPTIMIZATION', 'LOGS_ANALYSIS', 'WELL_ARCHITECTED', 'REGISTER_RESOURCE') NOT NULL;
