name: CI Build Server

permissions:
  contents: read
  pull-requests: read
  actions: read

on:
  pull_request:
    branches:
      - master
      - production
  push:
    branches:
      - master
      - production

jobs:
  build-server:
    runs-on: wlmdb-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies in server
        working-directory: ./server
        run: npm install

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Lint server code
        working-directory: ./server
        run: npm run lint

      - name: Test server code
        working-directory: ./server
        run: npm run test:nowatch
