name: Duplicate Issue

on:
  issue_comment:
    types: [created]

jobs:
  run:
    runs-on: wlmdb-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
      - name: Install Octokit
        run: npm install @octokit/rest
      - name: Run Duplicate Issue Script
        run: node .github/scripts/duplicate-issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.WLMDB_PROJECT_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}